### ISSUE TITLE
Support Cross-Language (R and Python) in Jupyter Notebook

### ISSUE THREAD

**Issue by partrita** [astral-sh/ruff#10504]
I mainly use Jupyter Notebook, and occasionally I use R in addition to Python code. My issue is that R code is sometimes mistaken for Python code in Ruff.

When I run Ruff in a folder with multiple Jupyter files, I encounter the following error:
```bash
> ruff --version
ruff 0.0.292
> ruff check .
error: Failed to parse 230726_Normalization.ipynb:cell 21:1:80: EOL while scanning string literal
error: Failed to parse 230828_scVelo_lympho.ipynb:cell 52:1:80: Unexpected token 'leiden_res0_4'
error: Failed to parse 230726_Normalization-Copy1.ipynb:cell 24:1:88: EOL while scanning string literal
error: Failed to parse 230726_FeatureSelection.ipynb:cell 11:1:84: EOL while scanning string literal
error: Failed to parse 230727_QC_draft.ipynb:cell 31:2:17: Unexpected token '='
```

Is there a way to exclude or bypass files written in R?
Thanks in advance.

**Comment by dhruvmanila** [comment]
To be clear, your Notebook mainly comprises of Python code but _some_ cells could contain R code - is that what you meant? Can you provide an example Notebook? We currently ignore any Notebooks which isn't Python. This information is available in the Notebook metadata which we use here:

https://github.com/astral-sh/ruff/blob/ebeea51b6a9832516de65af8d2050c4e1b06c92d/crates/ruff_notebook/src/notebook.rs#L380-L387

**Comment by partrita** [comment]
Yes, That's right. Here is my code.

```R
%%R -i data_mat -o doublet_score -o doublet_class

set.seed(123)
sce = scDblFinder(
    SingleCellExperiment(
        list(counts=data_mat),
    ) 
)
doublet_score = sce$scDblFinder.score
doublet_class = sce$scDblFinder.class
```

```python
adata.obs["scDblFinder_score"] = doublet_score
adata.obs["scDblFinder_class"] = doublet_class
adata.obs.scDblFinder_class.value_counts()
```
Ruff results.

```bash
230726_HL187_QC_WT.ipynb:cell 26:1:34: F821 Undefined name `doublet_score`
230726_HL187_QC_WT.ipynb:cell 26:2:34: F821 Undefined name `doublet_class`
```

I found out adding `F821` to ingore list in pyproject.toml is fix that.
But I hope better solutions.
Thanks

**Comment by dhruvmanila** [comment]
Thank you for providing the code. I'm assuming by `%%R` you're using the `rpy2` package (https://rpy2.github.io/doc/v3.5.x/html/generated_rst/notebooks.html). I'm a bit confused as to why are there syntax errors in the PR description but not through the code snippet you've provided in the comment. Can you clarify on this part?

I see that the error originates because the variable is defined in the R language cell while it's being used in the Python code cell. Currently, we don't support parsing R language which is why you're seeing the `F821` violations. I do see the use case for it but unfortunately it's not in our current scope.

I'd also recommend to upgrade the Ruff version if possible as you're using `0.0.292` which is a bit old.
