### ISSUE TITLE
Build ruff on Alpine s390x

### ISSUE THREAD

**Issue by raspbeguy** [astral-sh/ruff#10627]
Hello, I wish to fix ruff package on Alpine Linux. Currently the package won't build on s390x arch because of a dependancy that won't update its own dependancies. I'm talking about clearscreen which uses an old version on nix which contains a bug for s390x. The bug has been patched on nix but clearscreen seems almost abandoned.

Here is the issue https://github.com/watchexec/clearscreen/pull/20

I don't know rust so I can't contribute, but anyway I think it would be wise to get rid of a dependancy in such state.

**Comment by MichaReiser** [comment]
> The bug has been patched on nix but clearscreen seems almost abandoned.

It seems that the package is still maintained. The maintainer commented on https://github.com/watchexec/clearscreen/pull/20 with that they're happy to upgrade the `nix` package once the PR builds successfully. 

That's why I think the best forward is to help push the upgrade PR forward rather than vendoring, forking or replacing the dependency.

**Comment by charliermarsh** [comment]
I'll try to fix the upstream issue: https://github.com/watchexec/clearscreen/pull/21

**Comment by charliermarsh** [comment]
I was able to fix the issue in clearscreen, and the maintainer kindly cut a release. I've upgraded Ruff's version in https://github.com/astral-sh/ruff/pull/10869.

**Comment by raspbeguy** [comment]
many thanks @charliermarsh
