### ISSUE TITLE
`fmt: line-length-off` (or equivalent)

### ISSUE THREAD

**Issue by thejcannon** [astral-sh/ruff#10631]
👋 Howdy folks!

(I combed through the issues and didn't find one that looked like this)

This is a feature request for a `# fmt: line-length-off` (or equivalent) pair of pragmas that just disables line-length formatting, but continues to enable other formatting.

As an example:
```python
# fmt: line-length-off
NONREAD_MODES = [
    # update text modes
    "r+", "+r", "rt+", "r+t", "+rt", "tr+", "t+r", "+tr", "w+", "+w", "wt+", "w+t",
    "+wt", "tw+", "t+w", "+tw", "a+", "+a", "at+", "a+t", "+at", "ta+", "t+a", "+ta",
    "x+", "+x", "xt+", "x+t", "+xt", "tx+", "t+x", "+tx",
    # write text modes
    "w", "wt", "tw", "a", "at", "ta", "x", "xt", "tx"
    # update binary modes
    "rb+", "r+b", "+rb", "br+", "b+r", "+br", "wb+", "w+b", "+wb", "bw+", "b+w", "+bw",
    "ab+", "a+b", "+ab", "ba+", "b+a", "+ba", "xb+", "x+b", "+xb", "bx+", "b+x", "+bx",
    # write binary modes
    "wb", "bw", "ab", "ba", "xb", "bx"
]
# fmt: line-length-on
```

I want ruff to continue to format/lint/etc... the string quotes, the general "spacing", even the trailing comma... but keep my elements as they are.

That's it. Cheers y'all!

**Comment by MichaReiser** [comment]
This is an interesting idea but I don't think this can be easily implemented in the formatter, because I assume what you want is that the formatter preserves the lines as is, but otherwise formats the code. 

One challenge with this is that the formatter might decide to break a line for reasons other than the line length, e.g., because it's an array with a trailing comma. It's then impossible to preserve the lines as is. 

There's also the technical challenge that the formatting is interdependent. The statement formatting makes assumptions about how expressions get formatted to ensure the emitted source code remains syntactically correct (e.g., correctly indented).  Preserving the lines as they are means that the enclosing formatting can make fewer assumptions, e.g., it can no longer make assumptions about where comments are placed (or it makes wrong assumption and the formatter produces invalid syntax).

I think this feature request is mainly a symptom from the fact that Ruff and Black aren't good at formatting large arrays (just flattening them is a possibility but doesn't necessarily improve readability). I think we should focus our time on improving array formatting over improving suppression comment handling to fix up weaknesses in the formatter.

**Comment by ryan-williams** [comment]
`black` supports `# fmt: off` / `# fmt: on` to ignore blocks of code ([SO](https://stackoverflow.com/questions/58584413/black-formatter-ignore-specific-multi-line-code), [docs](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#ignoring-sections)).

Is there no way to disable `ruff` for specific lines or blocks of code?

**Comment by MichaReiser** [comment]
@ryan-williams Ruff supports `fmt: off` and `fmt: on`, see [docs](https://docs.astral.sh/ruff/formatter/#format-suppression). 

Yes, isort is not part of the formatter and uses different suppression comments but you already found the relevant documentation :)
