### ISSUE TITLE
`bad-exit-annotation` (`PYI036`) triggers on `typing.overload` definitions

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#11044]
Keywords searched in the issue tracker: PYI036, overload

Running `ruff check --select PYI036 --isolated` using Ruff version 0.4.0 on the file

```python
import typing
from types import TracebackType


class Foo:
    def __enter__(self) -> typing.Self:
        return self

    @typing.overload
    def __exit__(self, exc_type: None, exc_val: None, exc_tb: None) -> None: ...

    @typing.overload
    def __exit__(
        self,
        exc_type: type[BaseException],
        exc_val: BaseException,
        exc_tb: TracebackType,
    ) -> None: ...

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        pass
```

produces six `PYI036` errors (three for each overload definition). The expected behaviour is that no `PYI036` errors are raised, as these are overloads that describe legal calls rather than the complete implementation. This approach was recommended on [this blog post](https://adamj.eu/tech/2021/07/04/python-type-hints-how-to-type-a-context-manager/).

**Comment by charliermarsh** [comment]
@AlexWaygood - do you mind taking this one?

**Comment by AlexWaygood** [comment]
Yeah, good call — I think we should just skip any functions decorated with `@overload` for this check. Thanks for the report!

**Comment by AlexWaygood** [comment]
On second thought, we can provide some validation for overloaded functions. Slightly more fiddly, but definitely doable.

**Comment by charliermarsh** [comment]
Thanks Alex!

**Comment by bswck** [comment]
Some "related off-topic" from me, since I recently went through a similar thing.

There should be no need to write an overload if in either case we return `None`.
That's the thing for a PEP to propose the ability of unpacking unions of same-size tuples:

```py
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _typeshed import OptExcInfo  # tuple[None, None, None] | tuple[type[BaseException], BaseException, TracebackType]
    from typing_extensions import Unpack


class Foo:
    def __exit__(self, *args: Unpack[OptExcInfo]) -> None:
        pass
```

What Ruff might or might not want to do is [allow unpacking `_typeshed.ExcInfo` in the annotations of the `__exit__` signature](https://play.ruff.rs/b1bc564e-f213-414b-b7f6-51f85db32616), not require either `object` or full signature. But that would only make sense if we always expect an error to occur 🤷‍♀️
