### ISSUE TITLE
PLR0912: Pylint counts `try: ... except:` statements as single branch

### ISSUE THREAD

**Issue by Kakadus** [astral-sh/ruff#11205]
PLR0912 is not equivalent to pylint. The following function is accepted by pylint but rejected by ruff:
```py
def capital(country):
    if country == "Australia":
        return "Canberra"
    elif country == "Brazil":
        return "Brasilia"
    elif country == "Canada":
        return "Ottawa"
    elif country == "England":
        return "London"
    elif country == "France":
        return "Paris"
    elif country == "Germany":
        return "Berlin"
    elif country == "Poland":
        return "Warsaw"
    elif country == "Romania":
        return "Bucharest"
    elif country == "Spain":
        return "Madrid"
    elif country == "Thailand":
        return "Bangkok"
    elif country == "Turkey":
        return "Ankara"
    try:
        return None
    except:
        return "Some"
```
Pylint only detects 12 branches, while ruff counts 13. Is this a bug or a feature? If the latter, it should probably be documented. I can also imagine a setting, enabling/disabling this behavior

**Comment by MichaReiser** [comment]
The rule was added in https://github.com/astral-sh/ruff/pull/2550 but there's no conversation in that PR nor is there any change to the rule explaining if that divergence is indeed intentional. 

@chanman3388 as author of the rule. What's  your take on this? 

To me, counting `except` as its own branch does make sense. Because the except might or might not be executed. So the try block has two possible exit branches.

**Comment by charliermarsh** [comment]
It looks like the difference is whether the try _body_ counts as a branch? I'd say it should, probably. Although it's perhaps strange that `finally` counts as a branch, since it always runs? Ultimately, though, the rule is trying to capture some measure of complexity, and both the `try` body and the `finally` contribute to complexity in a way...

**Comment by charliermarsh** [comment]
I'd be fine to remove the body from the count though. It's a bit more consistent with Pylint and is pretty marginal either way.

**Comment by dhruvmanila** [comment]
Related: https://github.com/astral-sh/ruff/issues/11421
