### ISSUE TITLE
Inconsistency in line breaks (ruff formatter)

### ISSUE THREAD

**Issue by Romsik788** [astral-sh/ruff#11231]
Ruff version: 0.4.2
Python version: 3.11.6

Hi, team
I've found that the ruff formatter doesn't break a long string into a new line if the variable name is short. Here's a simple example:

main.py
```python
LOREM_IPSUM_DOLOR_SIT_AMET = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum"
LOREM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ut felis fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ut felis fermentum."
```
When you run `ruff format .`, you'll get the following:

main.py
```python
LOREM_IPSUM_DOLOR_SIT_AMET = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum"
)
LOREM_IPSUM = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ut felis fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ut felis fermentum."
```
I expected to see the following result:
```python
LOREM_IPSUM_DOLOR_SIT_AMET = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum"
)
LOREM_IPSUM = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ut felis fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ut felis fermentum."
)
```
I want to add that I didn't configure ruff beforehand and didn't use any configuration files.
Could you please confirm if this is expected behaviour or a bug?

**Comment by MichaReiser** [comment]
This is indeed the expected behavior in that it matches black's formatting ([playground](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGjAMRdAD2IimZxl1N_Wj5ZEv8xqI44fiQb7AsoFHl1Vp1Lav7QjxfCBH-_hTuVkU7aSGNSgBFimDt2G5iyPgNmw-DG1MQJe-zkcIExLHxtuD3zdrjWCmGJohxXpfMRhDoqWqQF-89668oJVZpyHR0QahLCvFDajTS6iNmrh-2NkJg5ea48nq-ulGE6_LoqIdQACvQVNazAYOMZ5cjbpB9jxrFxtTh9ksRiTORXY2-aMqm6w0iVBYzMBVxAsu3Ox7iFq1DxaP3tgcQA61V-OuYvmJMAAeABpAMAAOTWPiixxGf7AgAAAAAEWVo=))

Now, the logic isn't limited to whether the variable name is short, but whether the string will fit into the configured line-length when adding parentheses. 

Adding parentheses in your first example does make the string fit. The line with the string is only 75 characters wide

```python
LOREM_IPSUM_DOLOR_SIT_AMET = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum"
)
```

Now, parenthesizing the second example doesn't have the desired effect that the string fits into the line. Even when parenthesized, the string still has a width of 194. So ruff (and black) remove the parentheses. 

I'm personally all in favour of always adding the parentheses because parenthesizing at least reduces the amount by which the string exceeds the configured line length. However, we do favor black compatibility for now.

**Comment by Romsik788** [comment]
Hi @MichaReiser 
Thanks for the detailed feedback. In this case, I will close the task.
