### ISSUE TITLE
ruff removes valid noqa blocks

### ISSUE THREAD

**Issue by sandeshhardikar** [astral-sh/ruff#11306]
Hello ,

I am working my way to replace `yesqa` with `ruff` . When i run `ruff` on a sample python code , I have a feeling it removes all the `# noqa` blocks , even the valid ones .  

- ruff version used : 0.4.3
- code block
- `print("uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu")  # noqa: E501`
- command used : `ruff check --select RUF100 test.py --fix`
- Output :  `Found 1 error (1 fixed, 0 remaining).`

Ideally there should be nothing to fix , as the line length exceeds , but `ruff` removes the `# noqa` block . Please let me know if i am not using this functionality in a intended manner

**Comment by MichaReiser** [comment]
The noqa suppression here is not necessary because Ruff doesn't flag any lines that contain no whitespace, because it often indicates that there are no good split points for that line. 

> Ignores lines that consist of a single "word" (i.e., without any whitespace between its characters). [source](https://docs.astral.sh/ruff/rules/line-too-long/#why-is-this-bad)

I see the argument here that the line could be split after the `(`. I think that's something we can start doing once we have a way to cheaply get access to the parsed tokens (CC: @dhruvmanila)
