### ISSUE TITLE
`ruff check --fix --select I` seems to split imports incorrectly 

### ISSUE THREAD

**Issue by svfat** [astral-sh/ruff#11365]
Keywords: import, imports

When running `ruff check --fix --select I` on my code, I've noticed that it does not handle imports within round brackets correctly. Specifically, it unnecessarily splits grouped imports into separate blocks. 

**Example**:
Running the command on the following code:
```python
from aws_cdk import (
    aws_dynamodb as dynamodb,
    aws_lambda as lambda,
)
```

Results in:
```python
from aws_cdk import (
    aws_dynamodb as dynamodb,
)
from aws_cdk import (
    aws_lambda as lambda,
)
```

**pyproject.toml settings**
```[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.format]
indent-style = "space"
quote-style = "single"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "google"
```

**ruff version:**
ruff 0.4.4

**Comment by charliermarsh** [comment]
Can you try with:

```toml
[tool.ruff.lint.isort]
combine-as-imports = true
```

**Comment by charliermarsh** [comment]
I've confirmed in the playground that `combine-as-imports` leaves that as stable formatting: https://play.ruff.rs/0e4f5cd7-3ced-4a4a-89b6-c4670fe8b1d1

**Comment by Emerentius** [comment]
`combine-as-imports` isn't really the solution here, it's more of a workaround. The definition of that setting is "Combines as imports on the same line." which isn't what you may want.

The way I see it, you may prefer to have as-imports on their own line or on the same line:
```
from aws_cdk import (
    aws_dynamodb as dynamodb,
    aws_lambda as lambda,
)
```

```
from aws_cdk import aws_dynamodb as dynamodb, aws_lambda as lambda
```
and if enough imports appear on one line, the second formatting choice would fall back to placing each as-import on its own line.

I can't imagine anyone wanting to have the `from some_module import (` part repeated for every import. It balloons the import section because every as-import is now 3 lines big.
