### ISSUE TITLE
[red-knot] testing framework

### ISSUE THREAD

**Issue by carljm** [astral-sh/ruff#11664]
We want a nice way to write tests of our type inference.

Some prior art to consider:
* mypy: https://github.com/python/mypy/blob/master/test-data/unit/check-classes.test
* flake8-pyi: https://github.com/PyCQA/flake8-pyi/blob/main/tests/forward_refs_annassign.pyi
* typescript:
  * input: https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/AmbientModuleAndAmbientFunctionWithTheSameNameAndCommonRoot.js
  * symbols: https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/AmbientModuleAndAmbientFunctionWithTheSameNameAndCommonRoot.symbols
  * types: https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/AmbientModuleAndAmbientFunctionWithTheSameNameAndCommonRoot.types
  * errors: https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/ArrowFunction1.errors.txt
* pyright (similar to, probably derived from, typescript)

**Comment by KotlinIsland** [comment]
as someone who has worked on mypy a lot, i can attest to the tests being extremely painful to work with, to the point of scaring off many potential contributors

**Comment by carljm** [comment]
> as someone who has worked on mypy a lot, i can attest to the tests being extremely painful to work with, to the point of scaring off many potential contributors

Can you share any specifics about what features of the mypy test framework make it painful for you?

**Comment by KotlinIsland** [comment]
### syntax
mypy tests are written in a custom language - so no ide support at all

expected errors are written as the full output of running mypy
```py
1 + ""  # E: Unsupported operand types for + ("int" and "str")  [operator]
```
this is prone to mistakes and inadvertently writing comments that aren't expected errors

additionally, these messages are the full output of mypy, so it makes it hard to test specific things: column number, error code etc in isolation

additionally, when the text of an error changes slightly, it will require potentially thousands of tests to be updated for no practical reason

### config

the mypy tests are all intensely mysterious, each test suite behaves slightly differently and requires analysis of the implementation to determine the behaviour 

additionally, each test will run under its own (fake) context of standard library types. there are minimal and more complete versions of the stdlib to choose from for each test, specified with a `[builtins ...]` configuration key. this leads to really bad DX when mypy crashes because the types in the test are incomplete

additionally, because these test fixture stubs aren't accurate to typeshed, it leads to strong concerns regarding test accuracy 

ideally, i would want all tests to use full stdlib stubs, quell any performance concerns by loading the stdlib once and reusing it for each test. for assertions, i think the optimal solution would be a pattern matching style representation against the types and errors in a test would be ideal, perhaps something like:

I'm not sure if writing tests directly in python, or embedded within rust files would make more sense. I'm not very familiar with rust, so I'm not opinionated on a design for a rust implementation, so I can throw an idea for a pseudo python one:
```py
from redknot_test import Errors, expect_error, expect_type, GenericType

# errors are matched structurally, with optional fields that can be specified, depending on what is relevant 
expect_error(1 + "", Errors.Operator(left=int, right=str))

# expected types use the same pattern objects
# for example here we demonstrate that we can use `GenericType` as a placeholder, because in this contrived example, we only care about the type parameters type
expect_type([1], GenericType[int])
```

**Comment by DetachHead** [comment]
> - pyright (similar to, probably derived from, typescript)

pyright has two main types of tests as far as i know:

# fourslash tests
the fourslash test framework is vendored from the typescript repo. i think it's okay but has a lot of room for improvement, for example if you have a test with the following code:
  ```ts
  const code = `
// @Filename: /a.py
////foo
// @Filename: /b.py
////bar
     `
  ```
  the second file will silently be ignored because of the trailing whitespace on the newline after it (or something like that, i don't remember the exact details, but there are a lot of issues like that in fourslash)
# `validateResults` tests
these tests load a sample file and assert that it has the expected number of errors:
```ts
const result = typeAnalyzeSampleFiles(["foo.py"])
validateResults(result, /* errorCount */ 4)
```
the obvious problem here is that it's not checking what diagnostic codes they are, what line number they're on, etc. which increases the chance of regressions going undetected (eg. if an error stops occurring and a different unrelated error appears in a different spot)

**Comment by alex** [comment]
FWIW one pattern I've used successfully in the past is to be able to run tests in a "bless" mode, where gold copies are written, instead of asserted against. When you make a cross-cutting change the intentionally impacts many tests (e.g., changing a diagnostic message) you can then run in bless mode and review the diff to ensure everything looks right.

**Comment by carljm** [comment]
Yes, most of Ruff's tests are in this form (using `cargo insta`), and we also had a system like this for writing HIR lowering tests in the Cinder JIT.

We'll likely provide support for this as well, though maybe not in the initial version. I think this is a great approach for tests whose primary intent is to assert on full diagnostic output. I'm hesitant to make it the universal approach for all tests of type inference logic, because my experience with it is that it can sometimes lead to review fatigue, and actual logic bugs slipping through un-noticed in a pile of mostly-cosmetic changes.

**Comment by KotlinIsland** [comment]
mypy has this feature as well `> pytest --update-data`, it has led to many mistakes leaking past diff review though

**Comment by hauntsaninja** [comment]
I actually really really like having the full message in mypy's tests. It makes test cases much easier to review, I definitely recommend it.

I agree that fixtures are terrible and an impediment for mypy contributors.

Mypy also has other elements to its DSL (e.g. for incremental / LSP style test cases, different configuration options, different Python gating, etc). It also integrates nicely with pytest (so things like `-k` test selection work). You will likely want equivalents.

**Comment by carljm** [comment]
> I actually really really like having the full message as inline comments in mypy's tests. It makes test cases much easier to review and often motivates improvements to diagnostics, I definitely recommend it.

Hmm, I'm still quite skeptical here. It feels like it makes test cases effectively impossible to write without using `--update-data`, which is something I don't want. 

I don't think I understand "makes tests cases much easier to review". Does mypy have opaque (eg nuneric) error codes? I think error codes should be meaningful short text strings, which seems clear enough for review.

**Comment by carljm** [comment]
Thanks for the comments!

> Mypy also has other elements to its DSL (e.g. for incremental / LSP style test cases, different configuration options, different Python gating, etc). 

Yep, these are all important and in our plans. 

> It also integrates nicely with pytest (so things like -k test selection work),

We'll be integrating with `cargo test` (or nextest), so their usual test selection facilities will apply. 

> I find the cargo insta output in ruff noisy and somewhat hard to read though, since its not inline and context is duplicated)

Agreed, but this is hard to avoid if you want to test multi-line diagnostic output with context code frames (which I think is nice for users); it's hard to represent such diagnostics inline. 

> I'd also recommend integrating with mypy_primer at some point, am happy to help out with this too

Definitely, thank you!!

**Comment by hauntsaninja** [comment]
mypy's error codes are meaningful short strings. For me, the cognitive load saved during review is similar to why I wouldn't ever want my type checker to only output an error code, the context line and no message — but yeah, this might totally just be difference in taste. I think it also avoids any issue with multiple errors with the same code on one line + seeing the message in the context of the incorrect code does sometimes inspire better diagnostics.

**Comment by MichaReiser** [comment]
> We'll be integrating with cargo test (or nextest), so their usual test selection facilities will apply.

Yes, and no. It's going to be very similar to Ruff's test system which has been a pain point (at least for me). The test framework allows selecting a test-suite (a test file), but it won't be possible to select an individual test if the suite contains multiple tests.

> mypy's error codes are meaningful short strings (and it'd be kind of nice for red knot to match them whenever there isn't a reason not to).

We plan to use human-readable names over error codes. Hopefully, this will help with context.

**Comment by hauntsaninja** [comment]
To be clear, mypy's error codes are human readable. You can find a list of mypy's error codes at https://mypy.readthedocs.io/en/stable/error_code_list.html and https://mypy.readthedocs.io/en/stable/error_code_list2.html.
(I guess off-topic for this issue, but I'm happy to provide opinions on error codes as well!)

**Comment by DetachHead** [comment]
i don't like how mypy's errors work for a few reasons:

- too many of them are under the `misc` code
- the codes are all different to the corresponding options to enable/disable them (eg. the option to enable `redundant-cast` is called `warn-redundant-casts`)
- the options are inconsistently named (some are negative and some positive, eg.`--allow-untyped-globals` vs `--disallow-any-explicit` and some don't follow the `allow`/`disallow` pattern at all eg. `warn-return-any`)

the way pyright does it is better:

```toml
[tool.pyright]
# all rules are named in this consistent "report*" format
reportUndefinedVariable = true
```
```py
# the code for type ignore comments is the same as the option to enable them
asdf # type:ignore[reportUndefinedVariable]
```

this is the same as how ruff currently works (except ruff's codes aren't descriptive - #1773)

**Comment by hauntsaninja** [comment]
Yup, I agree with that. a) definitely too many things are still under misc, b) there shouldn't be separate flags corresponding to error codes at all (e.g. `--warn-redundant-casts` and others are legacy flags that existed before error codes)

**Comment by hauntsaninja** [comment]
Oh do note that pyright will not pay any attention to error codes on type ignore, only on pyright ignore, so your `asdf` example doesn't do what you'd want

**Comment by DetachHead** [comment]
true, i updated my example to use `pyright:ignore` instead which does look at the code
