### ISSUE TITLE
File directive `# flake8: noqa` also suppresses isort errors

### ISSUE THREAD

**Issue by albertvillanova** [astral-sh/ruff#11679]
The file directive `# flake8: noqa` does not only suppress `flake8` errors but also `isort` ones.

I would expect the flake8 directive to suppress only `flake8` errors, being equivalent to:
```
[tool.ruff.lint.per-file-ignores]
"my_filename.py" = ["F"]
```

This was the behavior before replacing `flake8`+`isort` with `ruff`.

**Comment by charliermarsh** [comment]
Thanks! From my perspective this is working-as-intended. `# flake8: noqa` is interpreted as "suppress all lint errors", and unorganized imports is a form of lint error.

Similarly:

```toml
[tool.ruff.lint.per-file-ignores]
"my_filename.py" = ["F"]
```

This wouldn't match Flake8's behavior either, since `# flake8: noqa` doesn't mean "Ignore the F rules", it means "Ignore all Flake8 rules", which includes the Pycodestyle rules (E, W) and any plugins you have installed. So that would be too narrow.

If you only want to ignore the `F` rules, I suggest using per-file ignores instead.

**Comment by albertvillanova** [comment]
Thanks for your reply, @charliermarsh.

Forget my above comment about the equivalence to ignoring F rules, which is not precise.

The key points are: for our files marked with the directive `# flake8: noqa`
- before using `ruff`, we were using `flake8`+`isort`
  - all Flake8 rules were ignored but not isort ones: the imports were sorted
- we replaced `flake8`+`isort` with `ruff` and we expected the same behavior
  - however now the imports are no longer sorted

If this behavior change is fine from your perspective, would you consider it worth mentioning explicitly in the docs to make it even clearer?

For example, maybe something like:
> Note that Ruff will treat Flake8's `# flake8: noqa` directive as equivalent to `# ruff: noqa`, thus suppressing all linting violations, not only Flake8 ones (e.g. also `isort`).

instead of:
> Note that Ruff will also respect Flake8's `# flake8: noqa` directive, and will treat it as equivalent to `# ruff: noqa`.
