### ISSUE TITLE
release 0.5.0 is different, was it intentional?

### ISSUE THREAD

**Issue by alexeagle** [astral-sh/ruff#12144]
I see that https://github.com/astral-sh/ruff?tab=readme-ov-file#usage still references `v0.5.0` so I wonder if the following was inadventent:

- tag is `0.5.0` where all prior releases used a `v` prefix to denote "this tag is a version"
- the artifacts uploaded to the GitHub release no longer have the version number in the filename
- the tar files now contain an extra directory segment named `ruff-[platform]` and the `ruff` binary is nested in that directory.

**Comment by dhruvmanila** [comment]
Relevant discussion: https://github.com/astral-sh/ruff/discussions/12078. But, to answer your question, yes it was intentional with the new release pipeline. It's mentioned in the [breaking changes section of the changelog](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#breaking-changes) and the release notes. I'll quote it here:

> * The released archives now include an extra level of nesting, which can be removed with `--strip-components=1` when untarring.
> * The release artifact's file name no longer includes the version tag. This enables users to install via `/latest` URLs on GitHub.

---

> I see that [astral-sh/ruff#usage](https://github.com/astral-sh/ruff?tab=readme-ov-file#usage) still references `v0.5.0` so I wonder if the following was inadventent:

Do you mean the reference in the pre-commit config? If so, then that uses the [version with `v` prefix](https://github.com/astral-sh/ruff-pre-commit/releases/tag/v0.5.0). I agree that this is a bit confusing. Maybe we should keep the deprecate the `v` prefix in pre-commit version to maintain consistency. /cc @charliermarsh

**Comment by alexeagle** [comment]
ah, thank you, I went looking through the breaking changes section and failed to find it. Will adjust our downstream scripts that install the release into Bazel.
