### ISSUE TITLE
Is it possible to disable formatting for chains with line-breaking? 

### ISSUE THREAD

**Issue by VladimirPodolian** [astral-sh/ruff#12312]
Ruff command:
```
ruff format
```

Default ruff.toml + these updates
```ruff.toml
line-length = 120
quote-style = "single"
```

Ruff version:
```
ruff 0.5.1
```

Hi there! I would like to use ruff on my work project and on myself project for selenium. But i'm facing an issue, that it formats lines like this 

```python
        self._action_chains\
            .move_to_element(self.element)\
            .move_by_offset(1, 1)\
            .move_to_element(self.element)\
            .perform()
```

To this 

```python
self._action_chains.move_to_element(self.element).move_by_offset(1, 1).move_to_element(self.element).perform()
```

Is it possible to disable formatting for chains with line-breaking on whole project ?

**Comment by MichaReiser** [comment]
Hi @VladimirPodolian 

I'm sorry. There's currently no option to disable chain formatting other than using suppression comments. 

```python
self._action_chains
    .move_to_element(self.element)
    .move_by_offset(1, 1)
    .move_to_element(self.element)
    .perform() # fmt: skip
```

But that turns off all formatting and is rather verbose. 

There's a tracking issue for improving [call chain formatting](https://github.com/astral-sh/ruff/issues/8598) overall. Unfortunately, chain formatting is especially hard in Python because line breaks are only allowed in parenthesized context (line-continuation tokens are an option but not something that the majority of the community prefers).
