### ISSUE TITLE
Linting on Jupyter Notebook fails after reordering cells

### ISSUE THREAD

**Issue by michue-work** [astral-sh/ruff#12573]
Hello, today I activated Ruff for Jupyter Notebooks and noticed some strange behavior I didn't see with normal Python files:

_After reordering the cells of a notebook, the editor window shows false-positives from Ruff linting._

**MWE**
`pyproject.toml`
```
[tool.ruff]
extend-include = [
    "*.ipynb",
]
```

`ruff.ipynb` (with --- denoting a new cell)
```
import random
---
f = random.random()
---
g = random.random()
```

After moving the third cell with `g = ...` to the second position, Ruff reports F401 on `import random`.

**Environment**
Operating System Windows_NT x64 10.0.19045
VS Code 1.91.1 (commit f1e16e1e6214d7c44d078b1f0607b2388f29d729)
Ruff extension v2024.36.0

**Comment by dhruvmanila** [comment]
> If I can help in narrowing the problem further down, please let me know.

Thanks but I've found out the root cause of this bug.

The reason this is occurring is because we model `NotebookCell` differently than the LSP spec internally but the change request is handled as per the spec. This means there's a mismatch in the expectations on how certain changes are requested to the server.

The difference is that we store the `TextDocument` _inside_ the `NotebookCell` itself while it should be stored elsewhere and `NotebookCell` would just act as a pointer to the text document corresponding the cell.

So, what happens in this case where the cells are moved but the content remains the same. VS Code sends this request as just moving the URIs and doesn't provide any content.

```json
{
    "notebookDocument": {
        "version": 1,
        "uri": "file:///Users/dhruv/playground/ruff/notebooks/issue.ipynb"
    },
    "change": {
        "cells": {
            "structure": {
                "array": {
                    "start": 1,
                    "deleteCount": 2,
                    "cells": [
                        {
                            "kind": 2,
                            "document": "vscode-notebook-cell:/Users/dhruv/playground/ruff/notebooks/issue.ipynb#W2sZmlsZQ%3D%3D",
                            "metadata": {
                                "metadata": {}
                            }
                        },
                        {
                            "kind": 2,
                            "document": "vscode-notebook-cell:/Users/dhruv/playground/ruff/notebooks/issue.ipynb#W1sZmlsZQ%3D%3D",
                            "metadata": {
                                "metadata": {}
                            }
                        }
                    ]
                },
                "didOpen": [],
                "didClose": []
            }
        }
    }
}
```

This goes back to https://github.com/astral-sh/ruff/pull/11864#discussion_r1639145836 as this explains why VS Code sends a request to close the text document corresponding to a notebook cell.
