### ISSUE TITLE
RET505 doesn't work with mixed space and tabs

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#12707]
ruff 0.5.6+419 (0b4d3ce39 2024-08-05)
```
ruff check *.py --select RET505 --no-cache --fix --preview --output-format concise --isolated
```

file content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
def f():
	if true:
	 return true
	else:
	 return false
```

error
```
python_data:4:2: RET505 Unnecessary `else` after `return` statement
Found 1 error.
[*] 1 fixable with the --fix option.

error: Fix introduced a syntax error in `crash` with rule codes RET505: unindent does not match any outer indentation level at byte range 33..34
---
 return falsern true
---

```

[python_code.py.zip](https://github.com/user-attachments/files/16505463/python_code.py.zip)

**Comment by diceroll123** [comment]
This _may_ be an upstream issue somehow. Uncertain, and can't look too much more into this until later.

`desired_indentation` for the `else` line is a tab, I checked by converting it to unicode -- which is `0x9`, as opposed to `0x20` for a space (32 in decimal)

But it seems to resolve into a space when the fix is applied, somehow.

Notes:
- I don't even see the same error, but I do still get an error (see code block below)
- It is 2:30 in the morning so take anything I say with a grain of salt 🤣

```python
def f():
        if True:
         return True
 return False
```

As you can see, tab resolves into 8 spaces.

**Comment by MichaReiser** [comment]
> This may be an upstream issue somehow. Uncertain, and can't look too much more into this until later.

What do you mean by an upstream issue? Do you mean an issue with the fix infrastructure (or anything that isn't the rule itself?)

**Comment by diceroll123** [comment]
Yep! I'm hoping I'm wrong, but definitely something weird going on.

**Comment by MichaReiser** [comment]
I haven't looked to deep but the result of `indented` looks of:

* `desired_indentation = "\t"`
* `&indented = " return false"`

https://github.com/astral-sh/ruff/blob/83b1c48a935f17869b9ee618faadc99213f83d95/crates/ruff_linter/src/rules/flake8_return/rules/function.rs#L878-L884

**Comment by diceroll123** [comment]
I've narrowed it down to the `ruff_python_trivia::textwrap::dedent_to`, invoked here https://github.com/astral-sh/ruff/blob/90e5bc2bd95e15086a3af81589cc2a1af298b6b2/crates/ruff_linter/src/fix/edits.rs#L324-L326

I've added these lines into that block,

```rust
println!("contents: {:?}", contents);
println!("indentation: {:?}", indentation.chars().next().unwrap() as u32);
println!("dedented to: {:?}", dedent_to(contents, indentation));
```

and the output is:

```
contents: "\t return False"
indentation: 9
dedented to: " return False"
```

So, the issue is upstream but not within the autofixing mechanisms, but in the `dedent_to` function.

**Comment by diceroll123** [comment]
Looking forward to future fuzzer issues!

**Comment by qarmin** [comment]
Well, now I only create issues when reproduction project can be used in real project.
If you want to check/fix some of not reported issues, you can check at this list(16280 broken files with info about exact rules that causes problems):

[a.7z.zip](https://github.com/user-attachments/files/16541656/a.7z.zip) (this is 7z file and needs to be renamed, because zip produced 30MB archive, that I couldn't attach here)


This files are broken with the latest ruff - `ruff 0.5.6+449 (6d9205e34 2024-08-08)`
