### ISSUE TITLE
A004 Preview Mode ExceptionGroup import in pre-3.11

### ISSUE THREAD

**Issue by CoolCat467** [astral-sh/ruff#13037]
Getting `A004 Import BaseExceptionGroup is shadowing a Python builtin` and `ExceptionGroup` errors raised in this case:
```python
if sys.version_info < (3, 11):
    from exceptiongroup import BaseExceptionGroup, ExceptionGroup
```
I would argue that this should not be the case. `BaseExceptionGroup` and `ExceptionGroup` do not exist in python versions prior to 3.11, and using the `exceptiongroup` package is commonly used for backwards compatibility.

Using ruff preview mode v0.6.1

**Comment by MichaReiser** [comment]
This makes sense to me, but we should only allow the use of `BaseExceptionGroup` and `ExceptionGroup` when inside a system.version < (3.11)` branch. I'm not sure if we have the necessary infrastructure today. wdyt @AlexWaygood ?

**Comment by AlexWaygood** [comment]
I'm quite hesistant to add the infrastructure to Ruff to support detecting which `sys.version_info` branch we're in. Generalised `sys.version_info` parsing would be tricky (though we'll have to implement it for red-knot to comply with PEP 484), and I'm not sure it's actually needed in this case. For this case, I think we could fix the issue by making the `is_python_builtin()` function smarter:
- The rule calls `shadows_builtin()` [here](https://github.com/astral-sh/ruff/blob/2edd32aa31446c81c245beb1230de26220a7d7e8/crates/ruff_linter/src/rules/flake8_builtins/rules/builtin_import_shadowing.rs#L37-L41).
- `shadows_builtin()` calls `is_python_builtin()` [here](https://github.com/astral-sh/ruff/blob/2edd32aa31446c81c245beb1230de26220a7d7e8/crates/ruff_linter/src/rules/flake8_builtins/helpers.rs#L9)
- `is_python_builtin()` is defined [here](https://github.com/astral-sh/ruff/blob/2edd32aa31446c81c245beb1230de26220a7d7e8/crates/ruff_python_stdlib/src/builtins.rs#L192). Unlike other [similar functions](https://github.com/astral-sh/ruff/blob/2edd32aa31446c81c245beb1230de26220a7d7e8/crates/ruff_python_stdlib/src/sys/known_stdlib.rs#L3-L585) in the `ruff_python_stdlib` crate, it assumes that all Python builtins have always been Python builtins; it doesn't take account of the fact that some builtins were added in newer Python versions. If we added a `minor_version` parameter, similar to `ruff_python_stdlib::sys::is_builtin_module` or `ruff_python_stdlib::sys::is_known_standard_library`, then we could take account of the `--target-version` the user has provided when deciding whether something is a Python builtin or not. Since @CoolCat467 clearly supports running Python <3.11 on their code, they'll probably be running Ruff with `--target-version py310` or lower.

**Comment by CoolCat467** [comment]
I think that using `--target-version` is a good solution
