### ISSUE TITLE
Unclear how to configure the quouting style in Zed extension

### ISSUE THREAD

**Issue by Yura52** [astral-sh/ruff#13090]
(key words: zed, quote-style)

Hi! I managed to make Ruff work in Zed with the official extension, but I don't understand how to configure the quoting style for the Ruff formatter: it always formats my code as if I set the quoting style to "double". Below, I added the relevant part of my `settings.json`. Some things to note:
- I tried `"quote-style"`, `"quote_style"`, `"quoteStyle"`, under the `"format"` key (as in the snippet below) and one level above (e.g. next to `"lineLength"`) -- nothing worked.
- At the same time it seems that all other pieces do have affect: I tested this by commenting and/or changing the below settings in both `"languages"` and `"lsp"` sections.

My environment:

```
macOS: 14.5
Ruff: 0.6.2 (Homebrew)
Zed: 0.149.5
Ruff extension: 0.0.2
```

```jsonc
"languages": {
    "Python": {
      "language_servers": ["ruff"],
      "format_on_save": "on",
      "formatter": [
        {
          "code_actions": {
            "source.organizeImports.ruff": true
          }
        },
        { "language_server": { "name": "ruff" } }
      ]
    }
  },
  "lsp": {
    "ruff": {
      "initialization_options": {
        "settings": {
          "targetVersion": "py310",
          "lineLength": 88,
          "lint": {
            "extendSelect": ["RUF", "UP", "E501", "E731"]
          },
          "format": {
            "quote-style": "single"
          }
        }
      }
    }
  },
```

P.S. Not an issue at all, but I was a bit surprised by `thisNamingStyle` instead of `this_naming_style` or `this-naming-style`, because the latter two options would be more consistent with other Zed settings and with `pyproject.toml`. But again, this is not a big deal.

**Comment by victorneo** [comment]
ruff seems to have two different set of settings: [lsp settings][1] and [ruff specific configuration options][2]

Notice that the options available under `format` for both sets of configuration options are different.

If my understanding is correct, `quote-style` is a ruff configuration option that can only be configured via one of the following files: [`pyproject.toml`, `ruff.toml`, or `.ruff.toml`][2]

`lsp` server settings that you configure in `settings.json` only support the following options, which is why it doesn't work when you put them in [`settings.json`][1]

[1]: https://docs.astral.sh/ruff/editors/settings/
[2]: https://docs.astral.sh/ruff/configuration/

**Comment by dhruvmanila** [comment]
What @victorneo said is correct. The server settings are different than the Ruff configuration. A few config keys are exposed as server settings but not all are, so `quote-style` isn't exposed. But, to account for them, there's `ruff.configuration` where you can provide a custom configuration path. Or, you can provide them at the project level as the server will consider those settings as well.

> P.S. Not an issue at all, but I was a bit surprised by `thisNamingStyle` instead of `this_naming_style` or `this-naming-style`, because the latter two options would be more consistent with other Zed settings and with `pyproject.toml`. But again, this is not a big deal.

It's because the server is agnostic to any editor that supports LSP. The naming style comes from the actual protocol https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/.

I'll mark this is resolved but feel free to ask any other questions that you might have.

**Comment by Yura52** [comment]
Thank you for the replies, I have managed to configure Ruff in Zed successfully! I should admit that, before knowing the details, in [the example](https://docs.astral.sh/ruff/editors/setup/#zed) in the Ruff documentation ([linked](https://zed.dev/docs/languages/python#code-formatting--linting) in the Zed documentation), the paragraph *"To configure the language server, you can provide the [server settings](https://docs.astral.sh/ruff/editors/settings/)"* sounded to me like "here is an example of customizing Ruff behavior through the editor config", and I thought that I could do the same with any setting. Perhaps, a short comment after that sentence can be helpful for newcomers.

**Comment by dhruvmanila** [comment]
> Perhaps, a short comment after that sentence can be helpful for newcomers.

Happy to accept a PR which makes it clear in the docs :)
