### ISSUE TITLE
F821 false positive when using ExceptionGroup

### ISSUE THREAD

**Issue by iurii-skorniakov** [astral-sh/ruff#13255]
version:  ruff 0.6.4, Python 3.11.6 
command: `ruff check --isolated example.py`
  
when using built-in `ExceptionGroup`
```python
class MyGroup(ExceptionGroup):
    def derive(self, excs):
        return MyGroup(self.message, excs)
```
ruff raises F821
```
example.py:1:15: F821 Undefined name `ExceptionGroup`
  |
1 | class MyGroup(ExceptionGroup):
  |               ^^^^^^^^^^^^^^ F821
2 |     def derive(self, excs):
3 |         return MyGroup(self.message, excs)
  |
```

**Comment by g3rv4** [comment]
seems like a regression from https://github.com/astral-sh/ruff/pull/3167

**Comment by charliermarsh** [comment]
Do you have a minimum Python version set, in your `pyproject.toml` or via `--target-version`? Otherwise, Ruff defaults to Python 3.8, and `ExceptionGroup` doesn't exist in that version.

**Comment by bonastreyair** [comment]
maybe it is another issue but for me it fails finding `anext` when using python3.11
it was working fine with previous version but now it fails because of that

I think the problem comes from here: https://github.com/astral-sh/ruff/pull/13172/files/de081b67c3072829c21cf8176a96baef64793ba7#diff-a5297ef4a78229f14881c57e472a6a79dc17e6a5a9244a676dfa6276d10f0dab

anext was before and now it is not present in that same list: https://github.com/astral-sh/ruff/pull/13172/files/de081b67c3072829c21cf8176a96baef64793ba7#r1746582057

**Comment by MichaReiser** [comment]
@bonastreyair could you share your configuration? `anext` is still in the builtins list but only when targeting Py310 or newer. 

* [Py38](https://play.ruff.rs/c16cf647-56f5-49b2-93a8-dc9ff83c4e5d)
* [Py311](https://play.ruff.rs/1252d490-e72e-48f4-a29d-8560b5fc1f34)

**Comment by bartfeenstra** [comment]
I started having similar problems, also with anext() and aiter().

Project.toml: https://github.com/bartfeenstra/betty/blob/0.4.x/pyproject.toml
Ruff failures: https://github.com/bartfeenstra/betty/actions/runs/10734022531/job/29768422099

Let me know if you need more details :)

**Comment by iurii-skorniakov** [comment]
Found my problem. 
I had incorrect configuration in subdirectory, which didn't extend root config. 
With correct configuration it works well
Thank you for your help!

**Comment by bartfeenstra** [comment]
Can we reopen this? I still have this problem, with a single root configuration file:
```
[lint]
extend-select = [
    'A',
    'B',
    'C4',
    'D',
    'F',
    'INT',
    'PT',
    'PTH',
    'SIM',
    'SLOT',
    'T20',
    'TCH',
]
ignore = [
    'D105',
    'D107',
    'D200',
    'D203',
    'D212',
    'D401',
    'F501',
    'PTH123',
    'SIM103',
]

[lint.per-file-ignores]
"betty/tests/*" = [
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D106',
]

```

**Comment by MichaReiser** [comment]
The fix is to specify the `requires-python` setting to a version that supports `ExceptionGroup`.

**Comment by bartfeenstra** [comment]
`requires-python = '~= 3.11'` in https://github.com/bartfeenstra/betty/blob/0.4.x/pyproject.toml, yet Ruff fails on ExceptionGroup, aiter, anext... I tried a simpler constraint of `requires-python = '>= 3.11'` but that did not seem to change Ruff's output.

**Comment by MichaReiser** [comment]
@bartfeenstra I don't think ruff picks up the `requires-python` constraint if you also have a `.ruff.toml` because the `.ruff.toml` takes precedence. You have to explicitly set the [`target-version`](https://docs.astral.sh/ruff/settings/#target-version) in the ruff.toml. The alternative is to move the ruff configuration into the `pyroject.toml`.

**Comment by bartfeenstra** [comment]
That makes sense! I'll give that a try shortly. Thank you!
