### ISSUE TITLE
Formatter: allow spaces in keyword arguments

### ISSUE THREAD

**Issue by nbraud** [astral-sh/ruff#13344]
Hi!

I ran into a minor snag with `ruff format`: a number of my projects format keyword arguments like `name = value,` for accessibility/readability reasons, which doesn't seem to be configurable yet.  For instance:
```py
with NamedTemporaryFile(
	dir = target.parent,
	prefix = target.stem,
	suffix = target.suffix,
	delete = False,
	mode = "w",  # otherwise the file would be opened in binary mode by default
) as new: ...
```
was reformatted as
```py
with NamedTemporaryFile(
	dir=target.parent,
	prefix=target.stem,
	suffix=target.suffix,
	delete=False,
	mode="w",  # otherwise the file would be opened in binary mode by default
) as new: ...
```

I tested under ruff 0.6.3, with an empty configuration, and searched for existing formatter issues containing `keywords` or `spaces`, prior to opening a new one.

**Comment by MichaReiser** [comment]
Hi @nbraud 

I prefer the formatting you described, which I'm familiar with from the JS ecosystem. However, we designed Ruff's style guide to follow PEP8, and the PEP8 recommendation for keyword arguments is not to use a space.

> Don’t use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter: 
> [[source](https://peps.python.org/pep-0008/#other-recommendations)]

Introducing an option that makes this configurable is a possibility. Still, we've been intentional about only supporting few configuration options because the formatter's goal is to reduce the formatting-related discussions on PRs and configuration options only shift those discussions from the PR to discussing configuration options. You can read more about the motivation in [Prettier's option philosophy](https://prettier.io/docs/en/option-philosophy).
