### ISSUE TITLE
provide a exit code for `ruff format` (without --check) for source file syntax error

### ISSUE THREAD

**Issue by trim21** [astral-sh/ruff#13419]
`ruff format /path/to/file` now have 2 exit code, 0 for success and 2 for errors.

> 0 if Ruff terminates successfully, regardless of whether any files were formatted.
> 2 if Ruff terminates abnormally due to invalid configuration, invalid CLI options, or an internal error.

I proposal to add a exit code 1 for source file syntax error.

This would be helpful for IDE/editor plugins to know it's expected error or unexpected internal error.

**Comment by MichaReiser** [comment]
Can you tell me more about your use case? Our long-term goal is that editors use the LSP to integrate Ruff because of performance and correctness concerns once we start adding multifile analysis support:

* Ruff needs to consider unsaved changes to avoid false positives. 
* Restarting Ruff on every keystroke would require re-checking your entire project and not just a single file. Yes, we plan to add some form of caching but the very least that Ruff has to do is to stat every referenced file to see if it has changed.
