### ISSUE TITLE
SIM910 does not work with **kwargs

### ISSUE THREAD

**Issue by spaceby** [astral-sh/ruff#13493]
SIM910 does not work with **kwargs

```python
def foo(**kwargs):
    # SIM910 not working
    a = kwargs.get('a', None)
```
https://play.ruff.rs/7f269c7d-e859-4672-b4ca-02d59036de87

**Comment by MichaReiser** [comment]
Thanks. 

Ruff doesn't seem to understand that `**kwargs` is a dictionary because `is_dict` returns `false`

https://github.com/astral-sh/ruff/blob/6963f75a14ac58886adf7302745fcda2b9fd3f21/crates/ruff_linter/src/rules/flake8_simplify/rules/ast_expr.rs#L276-L286

We should either improve our type inference to infer `dict` for `kwargs` or use our semantic model API to test whether the binding is a `**kwargs` argument.
