### ISSUE TITLE
Auto-disable ANN rules when a type-checker is detected

### ISSUE THREAD

**Issue by paduszyk** [astral-sh/ruff#13525]
Ruff is a great linter and formatter, we all don't have any doubts 👍🏼 Thank you guys for maintaining this project!

However, Ruff also includes some rules related to static type-checking, for example: ANN. 

Could it be possible to set up Ruff to automatically turn off those rules if a type-checker is configured, let us say `mypy`? In such a scenario, extra "type-checking" with Ruff looks like a redundancy to me.

**Comment by MichaReiser** [comment]
> Ruff is a great linter and formatter, we all don't have any doubts 👍🏼 Thank you guys for maintaining this project!

Thanks for the kind words

> Could it be possible to set up Ruff to automatically turn off those rules if a type-checker is configured, let us say mypy? In such a scenario, extra "type-checking" with Ruff looks like a redundancy to me.

I see the motivation for this but we very intentionally avoid reading configurations from other tools to avoid surprising behavior and incompatibilities (we don't know the other tool's version and ruff would break if the tool changes its configuration). 

> However, Ruff also includes some rules related to static type-checking, for example: ANN.

Some of those rules indeed overlap with what some type checkers do, but I consider their nature to be mostly linting (it enforces a specific style) rather than correct typing. I think it's best if users disable the rules manually if they know that their type checker of choice already covers them.

**Comment by paduszyk** [comment]
OK. Thanks for an elaborate answer. 🙂
