### ISSUE TITLE
ruff All checks passed! with error  `print.a()`

### ISSUE THREAD

**Issue by ArtemIsmagilov** [astral-sh/ruff#13566]
- code
  a.py
  ```python
  print.a()
  ```
  ruff
  ```bash
  ruff check a.py 
  All checks passed!
  ```
  pyright
  ```bash
  pyright a.py 
  Traceback (most recent call last):
  File "a.py", line 1, in <module>
    print.a()
    ^^^^^^^
  AttributeError: 'builtin_function_or_method' object has no attribute 'a'
  ```
- pyproject.toml by default
- ruff 0.6.5

Why does ruff miss this?

**Comment by AlexWaygood** [comment]
Hi, thanks for the issue! 

> * pyright
>       ```shell
>       pyright a.py 
>       Traceback (most recent call last):
>       File "a.py", line 1, in <module>
>         print.a()
>         ^^^^^^^
>       AttributeError: 'builtin_function_or_method' object has no attribute 'a'
>       ```

Hmm, that looks like an exception raised at runtime rather than a diagnostic that pyright would emit. Regardless, it's true that there are many errors that a type checker will catch but Ruff will currently not catch. Type checkers and linters are different kinds of tools that catch different kinds of errors; it's good to use both tools together rather than relying on one or the other.

The good news is that we're working on a type checking tool! You can follow our progress by watching commits to the various `red_knot_*` crates in Ruff. It'll be a while until it's ready, however; until then, I'd recommend that you use a type checker alongside Ruff to catch a broad range of statically detectable errors.
