### ISSUE TITLE
Why getting D203 as a warning?

### ISSUE THREAD

**Issue by naveenmaan** [astral-sh/ruff#13645]
I am working on trying to run a linter over my script. which has some lint issues. 
I want my output as JSON. But I am getting warning before my json.

```shell
python -m ruff check screen.py --output-format=json
```

```shell
warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.
warning: `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible. Ignoring `multi-line-summary-second-line`.
```

**Comment by AlexWaygood** [comment]
Hiya! The warning is telling you that you've enabled two rules that would tell you to do contradictory things. That's obviously going to cause some confusing output from Ruff :)

Do you have a `pyproject.toml`, `ruff.toml` or `.ruff.toml` file somewhere where you've listed the rules you wanted enabled? If so, maybe you could share that, and we might be able to see where the problem is.

The documentation pages for these rules can be found here: https://docs.astral.sh/ruff/rules/#pydocstyle-d

**Comment by MichaReiser** [comment]
The warning messages are written to `stderr`. To get the json output, redirect it e.g. to a file.

```
python -m ruff check screen.py --output-format=json > result.json
```
