### ISSUE TITLE
`ruff-format` does not account for `tool.ruff.lint`?

### ISSUE THREAD

**Issue by LecrisUT** [astral-sh/ruff#13760]
In our project we have set `tool.ruff.lint.ignore` to ignore `D210`. But when we tried to add ruff-format pre-commit, we encountered that the rule was still being applied ([example run](https://github.com/teemtee/tmt/pull/2844#issuecomment-2413366922)). This seems like a functionality bug, can someone investigate. Alternatively is there a rule planned to support the opposite approach, i.e. for one-line docstrings enforce having a single space separation between the `"""` markers?

**Comment by MichaReiser** [comment]
The sections in the `.lint` configuration only apply to the linter but not the formatter. The formatter always trims the whitespace from docstrings for consistent formatting and there's no option to change that behavior because we intentionally limit the formatter options and only support formatting styles with widespread adoption.

**Comment by LecrisUT** [comment]
I guess I will close the issue for now since it is an intentional design decision
