### ISSUE TITLE
Update PyCharm Configuration

### ISSUE THREAD

**Issue by IdoPort** [astral-sh/ruff#13765]
Since not specifying the check is deprecated we should change the picture to this one:
![PyCharmRuffConfiguration](https://github.com/user-attachments/assets/1eb617e1-5ec4-45cc-ac1c-10d80033213f)

**Comment by dhruvmanila** [comment]
Thanks for noticing. Yeah, we should update the screenshot.

**Comment by Lexachoc** [comment]
I installed `ruff` with `pip install ruff`

And in PyCharm, I have to use:
`$PyInterpreterDirectory$/Scripts/ruff`
instead of 
`$PyInterpreterDirectory$/ruff`

Maybe the image should be updated?

![Image](https://github.com/user-attachments/assets/933b9f0d-f5c9-4bbb-8b34-efb75a6f9042)

and maybe providing the texts would be even better:

Name: ruff
Description: Run ruff on project sources
Program: $PyInterpreterDirectory$/Scripts/ruff
Arguements: check $ContentRoot$
Working directory: $ContentRoot$

**Comment by dhruvmanila** [comment]
Happy to accept a PR that replaces the screenshot with a text equivalent, not sure what the format should look like but we can discuss / play around it in the PR.
