### ISSUE TITLE
Adding go-to-definition support to `ruff server`

### ISSUE THREAD

**Issue by JTKBowers** [astral-sh/ruff#14046]
Hi,

I'd like to add support for go-to-definition to the `ruff server`. I've had a play round and have a (very limited) proof of concept working. It can currently go to the definition when that definition is in the same file (so imported symbols just go to the `import` statement).

I'm happy to finish this feature and help with any maintenance if it fits with the project's goals and timelines, but before making it feature complete I've got a few questions:

1. I see that it's mentioned as a desired feature in the [roadmap discussion](https://github.com/astral-sh/ruff/discussions/10581#discussioncomment-9164433), but mostly in relation to the "red-knot" project. Would you accept a PR that works with the existing codebase, before that rewrite is complete?
1. What I currently have might still provide some value to users, even without being able to jump to a definition that's in another module. Is this something that you'd consider merging as-is, with the possibility to add more functionality later?
1. I have some ideas about how I might extend my branch to support definitions from other modules using existing code in the repository.
    1. Given my general unfamiliarity with the codebase, it's possible I've missed some showstoppers. Is there anything that you can think of there?
    2. The most straightforward way of resolving imports seems to be to use the `ruff_python_resolver`. I see that it's somewhat experimental and isn't currently integrated with the rest of the codebase. Is that a blocker?

Thanks!

**Comment by dhruvmanila** [comment]
Hey Jamie, thanks for opening this issue and providing your thoughts on this specific feature.

I appreciate you spending the time in understanding the codebase and implementing this feature but I'm not sure if this is going to be useful with the limitation that it can only resolve symbols within the same module. I think a lot of times the symbols will be coming from another module where this won't work. 

Currently, we recommend using another language server which can provide other capabilities like goto definition along with using the Ruff language server (for example, Pyright). This means that the goto definition request will be sent to the second language server because Ruff doesn't advertise it's support for it. If we start doing that in a limited manner, then the user experience will be limited. I'm also unsure of how the client will handle the two different responses to the same request, the responses will be different when the symbol is in a different module.

There's also additional context in https://github.com/astral-sh/ruff/pull/13883 which implements the same capability using red-knot.

**Comment by JTKBowers** [comment]
Hey Dhruv,

Thanks for your reply, and thanks for the link to the PR adding this functionality to red-knot. As that is further along than my effort I'll close this issue.
