### ISSUE TITLE
How to avoid automatically adding parentheses when exceeding line-length？

### ISSUE THREAD

**Issue by QJieWang** [astral-sh/ruff#14086]
I have looked up the documentation to avoid automatically adding parentheses, but found no methods. I prefer to use `\` rather than `()` when exceeding the line length. How can I change this?

**Comment by QJieWang** [comment]
https://github.com/astral-sh/ruff/issues/6271

I  do not want this feature and prefer to user `\` when change line.

**Comment by MichaReiser** [comment]
I assume you're using the formatter. 

Using parentheses is non-optional because Ruff follows black's style guide. You can read about the motivation at the end of [the *How Black wraps lines](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines) section. 

See also https://github.com/astral-sh/ruff/issues/14025
