### ISSUE TITLE
feature request: select ALL until a given version number

### ISSUE THREAD

**Issue by DaniBodor** [astral-sh/ruff#14464]
In the ruff settings, I like to select ALL rules and just ignore the ones that I dont use (which is a much shorter list than those I do). However, as the documentation already warns: "Use ALL with discretion. Enabling ALL will implicitly enable new rules whenever you upgrade." Indeed, I run into this quite frequently and it is a bit frustrating.

I now circumvent this issue by freezing the ruff version I use in the CI, but this is also not ideal, because that means that new improvements other than new rules also don't get implemented (e.g. bug fixes to existing rules, performance increase, etc). Also the script to fetch the version from pyproject.toml is kind of clunky.

I would like to request a setting where you can select ALL rules until a given version number. This would allow me to just specify installing ruff in CI, without fixing a version number. The settings will then take care of not selecting the newest rules, without me having to create a huge list of what to select.

The added benefit of this is that you can then more easily add all new rules at once, without having to go and check what new rules exist and decide one-by-one whether to implement them or not.

**Comment by MichaReiser** [comment]
Hi @DaniBodor 

Thanks for reaching out. I can see how using `ALL` with new ruff versions can be frustrating because `ALL` also includes very opinionated rules that not many don't agree with. That's also why we generally recommend that people don't use `ALL`. However, I can see why you and many others use it: Ruff doesn't provide a good alternative to `ALL`. There's no easy way to opt-in to a good default rule set that expresses "good community standards" but excludes the very nit-picky rules. We hope to address this shortcoming as part of the #1774 work. Unfortunately, this work is still far out. 

I don't think that a versioned-`ALL` selector is the right solution for the problem because it would give the wrong impression that it "freezes" the rules that run. But this is not the case, removed rules would no longer run even if they were previously selected with `ALL-0.5`. Supporting it would introduce a fair amount of complexity on our end.  

For now, I would suggest you pin the Ruff minor version in CI (or in your project. tool) and bump it every other month or so. You'll still get bug fixes this way and you won't be surprised by newly added rules, because we only ever introduce new rules in minor versions. Bumping the minor version gives you the opportunity to review the new rules and disable the ones you dislike.

**Comment by MichaReiser** [comment]
> Just figured I'd throw the idea out there and see what the response is :)

Yes, thanks for doing this. It's always great to hear from users and what problems they run into. I'll close this issue. Feel free to comment if you want to follow up on something and I can reopen.
