### ISSUE TITLE
RUF022 autofix should be marked unsafe if there are own-line comments between `__all__` items

### ISSUE THREAD

**Issue by phil65** [astral-sh/ruff#14552]
- I searched issues for `__all__`, couldnt see anything from today.

Since 0.8.0, ruff wants to sort my `__all__` array.
Thats generally very nice, but it also messes up something like.

``` python
__all__ = [
    # Core components
    "TaskManager",
    "TaskExecutor",
    # Models
    "TaskContext",
    "TaskProvider",
    "TaskResult",
    # Utilities
    "execute_concurrent",
]
```

gets sorted to:

``` python
__all__ = [
    # Models
    "TaskContext",
    "TaskExecutor",
    # Core components
    "TaskManager",
    "TaskProvider",
    "TaskResult",
    # Utilities
    "execute_concurrent",
]
```

So it messes up the groups.
Comments are only attached to one item instead of the group when sorting. I am not sure if that is a good assumption. Perhaps ignore sorting it when comments are inside the __all__ array?

Thanks! :)

**Comment by MichaReiser** [comment]
Thanks for opening this issue. 

Comments are difficult to get right because they have no semantic meaning. Is `# Core components` commenting `TaskManager` or the entire group? I also know that @AlexWaygood spent a lot of time to handle comments 


I see two possible changes instead of removing the fix entirely:

1. Mark the fix as unsafe if there are own-line comments because the fix might change the comment's semantic
2. Improve the heuristic. For example, the rule could implement sort-by-group similar to isort if some items are separated by blank lines

```py
__all__ = [
    # Core components
    "TaskManager",
    "TaskExecutor",

    # Models
    "TaskContext",
    "TaskProvider",
    "TaskResult",
    
    # Utilities
    "execute_concurrent",
]
```

Is formatted to


```py
__all__ = [
    # Core components
    "TaskExecutor",
    "TaskManager",

    # Models
    "TaskContext",
    "TaskProvider",
    "TaskResult",
    
    # Utilities
    "execute_concurrent",
]
```

I'm sure @AlexWaygood has some thought

**Comment by MichaReiser** [comment]
por

**Comment by AlexWaygood** [comment]
Thanks for opening the issue @phil65!

There's already some extensive documentation on the fix safety of this rule at https://docs.astral.sh/ruff/rules/unsorted-dunder-all/#fix-safety, and we note this problem there. However, I'm open to making this fix unsafe if there are any own-line comments. I think that's in the spirit of the policy on fix safety we recently adopted when it comes to comments. We should make the same change to `sort-dunder-slots` as well.

> 2\. Improve the heuristic. For example, the rule could implement sort-by-group similar to isort if some items are separated by blank lines

Unfortunately doing this would make the rule incompatible with the formatter, because the formatter will remove blank lines in between the items, which would then lead to the rule applying a different sort to the items than if the blank lines were present.

**Comment by MichaReiser** [comment]
> Unfortunately doing this would make the rule incompatible with the formatter, because the formatter will remove blank lines in between the items, which would then lead to the rule applying a different sort to the items than if the blank lines were present.

Right, I think we even discussed this back then. Thanks for reminding me.

**Comment by phil65** [comment]
Thank you for quick handling and a great piece of software. :)
