### ISSUE TITLE
RUF052 fix is unsafe when renaming TypeVars

### ISSUE THREAD

**Issue by oguzhanmeteozturk** [astral-sh/ruff#14798]
The automatic fix for RUF052 is unsafe when applied to TypeVar definitions. It renames ``` _T = TypeVar("_T")``` to``` T = TypeVar("_T")``` resulting in invalid code. The TypeVar name string must match the assigned variable name to maintain correctness, and the resulting T = TypeVar("_T") violates this requirement.

The underscore is often used to indicate private or internal TypeVars and is a common and valid pattern in python.

**Comment by AlexWaygood** [comment]
Thanks for opening the issue! Interesting, are you defining TypeVars inside functions? I thought RUF052 only applied inside function scopes

**Comment by oguzhanmeteozturk** [comment]
Tests define TypeVars internally sometimes

**Comment by AlexWaygood** [comment]
Just to make sure I understand -- something like this?

```py
def test_foo():
    _T = TypeVar("_T")
    
    def bar(x: _T) -> _T:
        ...  # some logic here
```

**Comment by oguzhanmeteozturk** [comment]
Yes, very similar. Not sure how relevant it is, but the exact point where it broke the test involves _T being passed as an argument to a FUT within a context (pytest.raises in this case).

**Comment by AlexWaygood** [comment]
Great, thanks. I'd argue that this is within the purview of RUF052 -- since the TypeVar is a local variable, it's private to the function even without the underscore; leading underscores are more usually used to indicate unused variables in function scopes, I think.

However, we obviously shouldn't be breaking TypeVar definitions by changing the name the TypeVar is assigned to without changing the string passed into the constructor. We either need to make our renaming logic more sophisticated and/or mark the autofix as unsafe in more cases.

Thanks for the report!
