### ISSUE TITLE
Incorrect resolution of nested modules

### ISSUE THREAD

**Issue by dcreager** [astral-sh/ruff#14826]
In #14825 I tried creating a test case that refers to a class in a nested module:

````md
```py path=a/b.py
class C: ...
```

```py
import a.b
x: type[a.b.C]
```
````

This produced an unexpected `unresolved-attribute` error:

> Type `<module 'System("/src/a/b.py")'>` has no attribute `b`

This suggests that our module resolution code is binding `a` to `a.b`, and not to `a` as the Python spec requires.

**Comment by MichaReiser** [comment]
@carljm this shouldn't be too hard to fix? Maybe something for a contributor to take on?

**Comment by carljm** [comment]
@MichaReiser I suggested @dcreager might take a look, good intro task for the module resolver.

**Comment by AlexWaygood** [comment]
Great spot @dcreager! There _is_ an existing TODO in the codebase regarding submodule imports, but this doesn't seem to be the same issue; I think it is a previously unknown bug.

For the record, the existing TODO is here:

https://github.com/astral-sh/ruff/blob/269e47be961d3eb95c0351e8f7006b71e083a6a4/crates/red_knot_python_semantic/src/types/infer.rs#L2155-L2163

The tests referenced by that TODO don't exist anymore, however; that's because they've been ported to mdtests. They're now here:

https://github.com/astral-sh/ruff/blob/269e47be961d3eb95c0351e8f7006b71e083a6a4/crates/red_knot_python_semantic/resources/mdtest/import/relative.md?plain=1#L114-L143

**Comment by dcreager** [comment]
Fixed in https://github.com/astral-sh/ruff/pull/14946 and https://github.com/astral-sh/ruff/pull/15026
