### ISSUE TITLE
Feature request: Ask formatter to ignore rules like the linter

### ISSUE THREAD

**Issue by ayjayt** [astral-sh/ruff#14948]
A way to set the formatter to ignore whole classes of rules just like the linter. 

```
[tool.ruff.format]
ignore = ['E701']
```

And then
```
if return_immediately: return
```

won't be formatted.

😬

**Comment by dylwil3** [comment]
My understanding is that, like `black`, the formatter is meant to be very opinionated and have as few configuration knobs to turn as possible. (Think of all the time saved arguing with your team about tabs and newlines! You can just shrug and blame it on Ruff 😄).

**Comment by MichaReiser** [comment]
Hi @ayjayt 

As @dylwil3 said, it's a philosophical decision that the formatter has only a few options. Many users see this as its main feature because it prevents them from having to make any formatting decisions. I always liked [the motivation outlined in Prettier's philosophy documentation](https://prettier.io/docs/en/option-philosophy).

This doesn't mean that we don't plan to add any new options, it only means that we have a relatively high bar for adding new formatter options and the options are mainly limited to configurations that don't change the code style, but some detail like what quotes you prefer.

Related issues: https://github.com/astral-sh/ruff/issues/8206
