### ISSUE TITLE
Strings after linebreak formatting are not combined

### ISSUE THREAD

**Issue by tobiasdiez** [astral-sh/ruff#15131]
The following code
```python
for unknown_key in kwds:
            raise TypeError("{} is not a valid keyword "
                            "argument".format(unknown_key))
```
is reformatted as
```python
for unknown_key in kwds:
            raise TypeError("{} is not a valid keyword " "argument".format(unknown_key))
```

The middle part `" "` should have been removed as well.

**Comment by AlexWaygood** [comment]
Thanks for the report! This is already fixed in the preview style for the formatter (which you can opt into using `tool.ruff.preview = true` in your pyproject.toml file, if you're using a pyproject.toml file). I believe it's also one of the changes to our formatter's behaviour that we plan to stabilise as part of our next minor release, which we're hoping to do in January

**Comment by MichaReiser** [comment]
Yes, exactly what @AlexWaygood said. See #13371 .

**Comment by tobiasdiez** [comment]
Awesome! Thank you both!
