### ISSUE TITLE
Feature request: ruff format toml files

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/ruff#15152]
Since ruff [can lint pyproject.toml](https://docs.astral.sh/ruff/rules/invalid-pyproject-toml/), it could also be able to format toml files.

Specially with `uv` already editing/generating these files, there is likely lots of in-house knowledge to make it happen.

**Comment by inoa-jboliveira** [comment]
> This seems to be a duplicate of [#10738](https://github.com/astral-sh/ruff/issues/10738). See also [#10227](https://github.com/astral-sh/ruff/issues/10227) and [#9244](https://github.com/astral-sh/ruff/issues/9244).

Seems right. I did try searching but github search sucks (or skill issue on my side). 

The problem with I see with these other Issues is they ask for the moon and stars: extensible or plugin support, several languages. I am here advocating for a file format that is very relevant for the python ecosystem and possibly not much effort to implement.

**Comment by MichaReiser** [comment]
> Seems right. I did try searching but github search sucks (or skill issue on my side).

My GitHub search is a mystery to me. I often have to click through pages even if I know that there's another issue that is exactly what I'm looking for.

> The problem with I see with these other Issues is they ask for the moon and stars: extensible or plugin support, several languages. 

That's fair. But I think #10738 still captures the feature you're asking for, and I see it as very likely that TOML will be one of the first languages we'll support because I agree on its importance.
