### ISSUE TITLE
Is it possible to version documentation?

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#4159]
https://pypi.org/project/mike/
> **mike** is a Python utility to easily deploy multiple versions of your [MkDocs](http://www.mkdocs.org/)-powered docs to a Git branch, suitable for deploying to Github via `gh-pages`. To see an example of this in action, take a look at the documentation for [bfg9000](https://jimporter.github.io/bfg9000).

**Comment by charliermarsh** [comment]
This looks reasonable if anyone is ever interested in it. The main problem is that we don't use a `gh-pages` branch.

**Comment by zanieb** [comment]
@charliermarsh we did this over at Prefect and opted for a separate repository to contain all of the built documentation rather than using a branch in the primary repository. On each release of the primary repository, a job is triggered in the documentation repository which pulls the release source, builds the documentation, checks it into the repository, and opens an auto-merged pull request for the version. On merge to main, it's deployed via Netlify to production. Unfortunately the documentation repository is not public at this time so I don't have an example to point to (cc @desertaxle changing it to public was something I was working on if you have the time to finish the process ❤️).

**Comment by zanieb** [comment]
Closing in favor of https://github.com/astral-sh/ruff/issues/9507
