### ISSUE TITLE
Allow for testing of packages in integration tests

### ISSUE THREAD

**Issue by chanman3388** [astral-sh/ruff#4160]
It is my understanding that we cannot use folders/packages in integration tests.
For the moment I believe that we just use `ruff::test::test_path` to test a specific module, but I think it should be easy enough to make a similar function, or perhaps even a parent function that calls `test_path` not unlike how `ruff_cli::commands::run` lints all the files in parallel (I have not yet fully thought through the implementation).

I am happy to implement this.

**Comment by MichaReiser** [comment]
Adding support for testing multiple file would be cool to have to test any multi-file analysis that we plan to build properly. 

Ideally, I would prefer a single testing infrastructure for single file and multi-file analysis (we can have helpers for single-file or multi-file test cases) because the testing infrastructure re-implements the linting orchestration layer of ruff and any divergence in it from ruff's actual behavior results in a false sense of safety. That's why I think we should strive to have an as thin-as-possible testing implementation and share it if possible.

**Comment by chanman3388** [comment]
I've had a little look into this further and had a few more questions. I was hoping to mirror the orchestration layer but I think this approach may be too heavy-handed. We could maybe do something like, detect the path we want to test is a python module or package then simply call `test_path` on each? This feels like it should work as we use `packaging::detect_package_root` to detect the package? Would something like that be sufficient?

**Comment by charliermarsh** [comment]
Going to close this for now to keep the issue tracker actionable.
