### ISSUE TITLE
__dunder_blunder___ support

### ISSUE THREAD

**Issue by gitpushdashf** [astral-sh/ruff#4592]
Hi, everyone!

I'm not sure if this rule would cover this or not: https://beta.ruff.rs/docs/rules/dunder-function-name/

I made a dunder blunder today, with an extra `_`. Despite `ruff`, `pyright`, and `pytest`, nothing caught my error. It was for a `def __lt__()`-type function.

This seems *fairly* trivial, at first glance, at least compared to other rules. Those extra underscores can really blend in with eachother.

If the dunder-function-name does cover it, maybe it could be documented? Or maybe two separate rules would be ideal?

Anyway, Ruff is an awesome project. I don't know if there's an existing Python tool that does this check.

**Comment by ngnpope** [comment]
This is an interesting one. I've also found mistakes like `__lte__()` instead of the correct `__le__()`, etc. which would be good to catch. This might be easily done by having a set of known dunders and comparing. Should be easy enough to do a "Did you mean X?" too.

It's worth noting that Python's enum has some [custom dunder methods](https://docs.python.org/3/library/enum.html#supported-dunder-names) and it may also be good to extend support for the [custom sunder methods](https://docs.python.org/3/library/enum.html#supported-sunder-names) too? (I've mistakenly used `def __missing__(...):` instead of `def _missing_(...):` before.)

**Comment by gitpushdashf** [comment]
> This is an interesting one. I've also found mistakes like `__lte__()` instead of the correct `__le__()`, etc. which would be good to catch. This might be easily done by having a set of known dunders and comparing. Should be easy enough to do a "Did you mean X?" too.
> 
> It's worth noting that Python's enum has some [custom dunder methods](https://docs.python.org/3/library/enum.html#supported-dunder-names) and it may also be good to extend support for the [custom sunder methods](https://docs.python.org/3/library/enum.html#supported-sunder-names) too? (I've mistakenly used `def __missing__(...):` instead of `def _missing_(...):` before.)

Probably! Sunder method mistakes would be good to catch as well.

**Comment by charliermarsh** [comment]
I think we now support this via [`bad-dunder-method-name`](https://docs.astral.sh/ruff/rules/bad-dunder-method-name/).
