### ISSUE TITLE
Complete Jupyter notebook integration

### ISSUE THREAD

**Issue by dhruvmanila** [astral-sh/ruff#5188]
Meta issue to keep track of the remaining tasks before shipping Jupyter notebook native integration:

- [x] #4727
- [ ] #5189
- [ ] Add support for viewing Jupyter Notebooks in the playground
- [x] #5190

## Formatter Support

- [ ] ~Add support for `IpyEscapeCommand` token in [`SimpleTokenizer`](https://github.com/astral-sh/ruff/blob/036035bc502cd13dbb555385a3e6398f89b977a5/crates/ruff_python_trivia/src/tokenizer.rs) (if required)~
- [x] Add support for formatting `StmtIpyEscapeCommand`
- [x] Add support for formatting `ExprIpyEscapeCommand`
- [x] https://github.com/astral-sh/ruff/pull/7749

## Editor Integrations

- [x] https://github.com/astral-sh/ruff-vscode/issues/256 - I think this will probably involve changes in `ruff-lsp` so that other editors can benefit as well.

## IPython Syntax Handling (`%`, `!`, etc.)

- [x] #5030

### Ruff

- [x] #6090
- [x] #6087

### Proposed new rules

- [ ] Empty magic command (`%`) (Autofix: remove the statement)
- [ ] Magic command contains whitespace between the prefix and command value (`% matplotlib inline`) (Autofix: remove all the whitespaces) (Only valid for `%` magic prefix)

### Existing rule changes

- [x] #6116
- [x] #6672 

_I'll be looking at other related rules and update this issue accordingly_

### Parser

- [x] #6359
- [x] #6357
- [x] https://github.com/astral-sh/RustPython-Parser/pull/23
- [x] https://github.com/astral-sh/RustPython-Parser/pull/30
- [x] https://github.com/astral-sh/RustPython-Parser/pull/31

## Autofix for Jupyter Notebook

- [x] https://github.com/astral-sh/ruff/issues/1218

### Implementation

- [x] https://github.com/astral-sh/ruff/pull/5114
- [x] https://github.com/astral-sh/ruff/pull/5076
- [x] https://github.com/astral-sh/ruff/pull/5028
- [x] https://github.com/astral-sh/ruff/pull/4665

**Comment by charliermarsh** [comment]
My main question would be: at what point do you think we can remove the feature flag, and open this up to users? (Maybe we're already past that point!)

**Comment by dhruvmanila** [comment]
I do think we're ready except that without the (1) task above Ruff might give false positives. Without that we would ignore any cell which contains magic commands. Now, we would also ignore if it contains valid Python code. It could be that a variable is defined in that cell and is being referenced in another cell. Here, we might trigger undefined variable. Similar example can be given for imports.

I see this a lot for `%matplotlib inline` command: https://sourcegraph.com/search?q=context:global+lang:%22Jupyter+Notebook%22+%25matplotlib+inline&patternType=standard&sm=1&groupBy=repo

**Comment by dhruvmanila** [comment]
What do you think about releasing this under experimental? I'm not sure what would that look like but maybe we don't add the `*.ipynb` to `include` and ask users to explicitly opt in to that.

**Comment by charliermarsh** [comment]
Yeah, I think it would be reasonable to release it now (even without magic handling) and omit `*.ipynb` in `include`, so users need to opt-in explicitly. We can market it as experimental to get feedback. We can include it in the next release IMO.

We should also add the magic command support, but doesn't have to block if it's opt-in :)

**Comment by charliermarsh** [comment]
(To be explicit: we could just remove the flag now.)

**Comment by jpmckinney** [comment]
I'm not sure if this deserves its own issue, but: Would it be possible to use `extend-include = ["*.ipynb"]` and `ruff format` to **only** re-format the Python code in cells, and **not** the ipynb file itself?

My users typically edit notebooks in Google Colab. Google Colab uses two-space indentation in the ipynb file, instead of the typical one-space indentation. `ruff format` currently re-indents with one space. As such, edit history becomes difficult/impossible to track, because effectively every line gets rewritten between the user saving from Google Colab (changing to 2 spaces) and CI running `ruff format` (changing to 1 space).

Google Colab also puts keys like metadata, nbformat, nbformat_minor at the top of the file, but `ruff format` moves these to the bottom. `ruff format` also changes the order of `execution_count`, `outputs`, etc.

I would love to be able to opt out of ipynb formatting, so that only the Python code inside cells is reformatted.

**Comment by dhruvmanila** [comment]
(I think it deserves its own issue, we can discuss it there :))

**Comment by dhruvmanila** [comment]
Closing this as completed. The only thing remaining is to support `--add-noqa`.
