### ISSUE TITLE
pyupgrade in pyi files doesn't respect target-version

### ISSUE THREAD

**Issue by trim21** [astral-sh/ruff#5641]
rules like `UP007 [*] Use X | Y for type annotations` doesn't respect target-version in type stub (pyi files)

pyi type `Dict[...]` are rewrite to `dict[...]` with `target-version='py37'` anyway

**Comment by charliermarsh** [comment]
Thanks for filing! This is intentional. Since stub files are never executed by the interpreter, and only exist to support static analysis, `.pyi` files are always treated as if `from __future__ import annotations` is enabled, i.e., you can always use features like built-in generics and the pipe union syntax: https://typing.readthedocs.io/en/latest/source/stubs.html#syntax. So, we respect that behavior and allow rewriting regardless of the current Python version.
