### ISSUE TITLE
UP007 false negative with quoted type

### ISSUE THREAD

**Issue by dorschw** [astral-sh/ruff#5706]
UP007 won't recognize cases like 
```python
from typing import Optional


def foo(_: Optional["myclass"]):
    pass
```

While it recognizes
```python
from typing import Optional


def foo(_: Optional[myclass]):
    pass
```

reproduces with 0.0.277 and on the playground

**Comment by charliermarsh** [comment]
I think this follows pyupgrade’s behavior, but I need to look into if that’s true, and why.

**Comment by charliermarsh** [comment]
I think this is the correct behavior (in some cases). E.g., this fails for me on 3.11:

```python
from typing import Optional


def foo(_:  "myclass" | None):
    pass
```

With:

```console
Traceback (most recent call last):
  File "/Users/crmarsh/workspace/ruff/foo.py", line 4, in <module>
    def foo(_:  "myclass" | None):
                ~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'
```

However, it's _sometimes_ okay, e.g. this is fine:

```python
from typing import Optional

class MyClass:
    pass


def foo():
    x: "MyClass" | None = MyClass()

foo()
```

But this is not:

```python
from typing import Optional

class MyClass:
    pass


def foo():
    x: "MyClass" | None = MyClass()

    def bar(x: "MyClass" | None):
        pass

foo()
```

It has to do with when Python evaluates annotations at runtime (e.g., any parameters to functions need to be evaluated at runtime because they get added to `__annotations__`). We can support this in more cases but it's not safe to do everywhere.
