### ISSUE TITLE
S101 (assert detected) conflicts with mypy type narrowing

### ISSUE THREAD

**Issue by messense** [astral-sh/ruff#6051]
```python
from typing import Any


def fn(x: Any):
    assert isinstance(x, int)
```

ruff 0.0.280 gives

```bash
$ ruff --select S101 t.py
t.py:5:5: S101 Use of `assert` detected
Found 1 error.
```

But sometimes `assert isinstance(...)` is used for mypy [type narrowing](https://mypy.readthedocs.io/en/latest/type_narrowing.html#type-narrowing-expressions).

**Comment by charliermarsh** [comment]
Unfortunately... I think this is probably unresolvable. S101 is a security-related check (to avoid using `assert` statements as a means of preventing code execution, e.g., for authorization, since `assert` statements can be disabled at runtime via `-O`), so the bar to making exceptions needs to be quite high, and I don't see how we can know that an assertion is being used exclusively for type narrowing but _not_ for such runtime-related enforcement.

I'd probably recommend just disabling `S101` or even the `S` rules altogether outside of security-sensitive contexts. If you're in a security-sensitive context, and _are_ enforcing these rules, then I think it's probably _correct_ to require case-by-case `# noqa` disablement.
