### ISSUE TITLE
SyntaxError when unpacking sequences inside of []

### ISSUE THREAD

**Issue by Morkunas** [astral-sh/ruff#6078]
Ruff version: 0.0.280
Python version: 3.8.10

Command run:
`ruff check code.py`
Contents of `code.py`:

```
c = {}
c[(*[1, 2]), 3] = 4
```

This is a valid Python 3.8 code, which creates a dictionary `{(1, 2, 3): 4}`. The above invocation of ruff however throws this error:

`E999 SyntaxError: cannot use starred expression here`

**Comment by charliermarsh** [comment]
Thanks!

**Comment by MichaReiser** [comment]
Fixing this requires that our parser supports parsing different python version by passing a *python version* to the parser.

**Comment by charliermarsh** [comment]
Why is that required? Don't we just parse a superset?

**Comment by charliermarsh** [comment]
But that’s valid syntax under Python 3.12. Do you mean, if you target Python 3.7?

**Comment by charliermarsh** [comment]
And I believe that _is_ what the parser does today. We parse all valid Python 3.12 syntax, even if the user is targeting earlier Python versions. But I may be misunderstanding your comment.

**Comment by MichaReiser** [comment]
> But that’s valid syntax under Python 3.12. Do you mean, if you target Python 3.7?

I need to double check but I pasted it into Python 3.12 and it failed with a syntax error

**Comment by charliermarsh** [comment]
Huh, interesting... I agree, it seems to work on Python 3.8 but not later versions. That's very confusing to me, I had thought that they'd increased the number of locations in which starred expressions were supported, not that they'd made backwards incompatible changes. We can't really support this right now though, since we don't support version upper-bounds, only lower-bounds.

**Comment by zanieb** [comment]
Yeah interesting...

```
Python 3.7.17
OK

Python 3.8.17
OK

Python 3.9.17
  File "<string>", line 1
    c = {}; c[(*[1, 2]), 3] = 4
               ^
SyntaxError: can't use starred expression here

Python 3.10.12
  File "<string>", line 1
    c = {}; c[(*[1, 2]), 3] = 4
               ^^^^^^^
SyntaxError: cannot use starred expression here

Python 3.11.4
  File "<string>", line 1
    c = {}; c[(*[1, 2]), 3] = 4
               ^^^^^^^
SyntaxError: cannot use starred expression here

Python 3.12.0b4+
  File "<string>", line 1
    c = {}; c[(*[1, 2]), 3] = 4
               ^^^^^^^
SyntaxError: cannot use starred expression here
```

**Comment by charliermarsh** [comment]
My best guess is that this was an unintentional change from [PEP 646](https://peps.python.org/pep-0646/#grammar-changes).

**Comment by zanieb** [comment]
Agreed — I haven't found a bug report upstream yet. I could open one unless someone else knows of an existing issue.

**Comment by charliermarsh** [comment]
I read through this issue in CPython which was flagged to me on [Twitter](https://twitter.com/isidentical/status/1684683536790335489): https://github.com/python/cpython/issues/84811#issuecomment-1093871867.

It sounds like Guido effectively considers it a bug that this worked in earlier versions of Python 3. I am inclined to mark this as `wontfix`, since it stopped working some time around Python 3.9 ([Twitter](https://twitter.com/mgdotdev/status/1684615055692951552)) and wasn't an intentional part of the grammar.
