### ISSUE TITLE
Line number anonymization in snapshots?

### ISSUE THREAD

**Issue by harupy** [astral-sh/ruff#6097]
Does line number anonymization help minimize snapshot changes in PRs?

Example:

```
---
source: crates/ruff/src/rules/flake8_pytest_style/mod.rs
---
PT012.py:L:L: PT012 `pytest.raises()` block should contain a single simple statement
   |
LL |   def test_error_multiple_statements():
LL |       with pytest.raises(AttributeError):
   |  _____^
LL | |         len([])
LL | |         [].size
   | |_______________^ PT012
   |
```

**Comment by zanieb** [comment]
I like the idea personally. Curious for others' thoughts!

**Comment by harupy** [comment]
How I got the snapshot above:


```diff
diff --git a/crates/ruff/src/message/diff.rs b/crates/ruff/src/message/diff.rs
index c665578c2..1dba0222d 100644
--- a/crates/ruff/src/message/diff.rs
+++ b/crates/ruff/src/message/diff.rs
@@ -90,6 +90,10 @@ impl Display for Diff<'_> {
                     let old_index = change.old_index().map(OneIndexed::from_zero_indexed);
                     let new_index = change.new_index().map(OneIndexed::from_zero_indexed);
 
+                    #[cfg(test)]
+                    write!(f, "L L |{}", line_style.apply_to(sign).bold())?;
+
+                    #[cfg(not(test))]
                     write!(
                         f,
                         "{} {} |{}",
diff --git a/crates/ruff/src/message/text.rs b/crates/ruff/src/message/text.rs
index ee27ae28f..2acfa7314 100644
--- a/crates/ruff/src/message/text.rs
+++ b/crates/ruff/src/message/text.rs
@@ -101,6 +101,18 @@ impl Emitter for TextEmitter {
                 start_location
             };
 
+            #[cfg(test)]
+            writeln!(
+                writer,
+                "L{sep}L{sep} {code_and_body}",
+                sep = ":".cyan(),
+                code_and_body = RuleCodeAndBody {
+                    message,
+                    show_fix_status: self.flags.intersects(EmitterFlags::SHOW_FIX_STATUS)
+                }
+            )?;
+
+            #[cfg(not(test))]
             writeln!(
                 writer,
                 "{row}{sep}{col}{sep} {code_and_body}",
@@ -284,6 +296,8 @@ impl Display for MessageCodeFrame<'_> {
                 color: false,
                 #[cfg(not(test))]
                 color: colored::control::SHOULD_COLORIZE.should_colorize(),
+                #[cfg(test)]
+                anonymized_line_numbers: true,
                 ..FormatOptions::default()
             },
         };

```

**Comment by dhruvmanila** [comment]
I really like the idea! Most of the times I try to add the test cases at the end of the file to avoid confusing diffs unless the test case belongs to a "group" of related cases.

I think the `row:col` pair in the diagnostic message should be present. Also, instead of anonymous line numbers we could just eliminate them? Not sure if they're actually useful.

Any other thoughts are appreciated!

**Comment by harupy** [comment]
@dhruvmanila Thanks for the comment!

> I think the row:col pair in the diagnostic message should be present

to make sure the error location is correct?

> Also, instead of anonymous line numbers we could just eliminate them? Not sure if they're actually useful.

We could if the `annotate-snippets` crate supports this :)

**Comment by MichaReiser** [comment]
I generally like the idea because it makes reviewing changes easier but there are a few things that are unclear to me / need to be tested differently:

* Our infrastructure for computing line indices, line numbers, relevant diff windows, and printing the diagnostics is mainly tested with the rule tests. Removing/Anonymizing the line numbers from the snapshots would reduce the coverage to like 2 tests... 
* One of my long-term quests is to add support for multi-frame diagnostics. Meaning you can add multiple code frames to a single diagnostic. Having line numbers can then be useful to understand the different frames (that could even be from different files)

What I understand is that the main problem is that the line numbers change every time we add a new test case to a file. Would it be possible to better isolate individual tests cases instead?

**Comment by charliermarsh** [comment]
I also like the idea but I have a similar reaction to Micha. Separately, the line numbers make for bad diffs on-change but they actually are useful when interpreting the snapshot outside of a code review.

> Would it be possible to better isolate individual tests cases instead?

This seems like it would help a lot, but is also challenging to achieve.

**Comment by zanieb** [comment]
I've also thought about this a bit more and I think we probably won't want to make this change. Retaining test coverage and ease of interpreting snapshots seems important. I've opened a discussion to talk about this problem in general: https://github.com/astral-sh/ruff/discussions/6129

I hope you don't mind if I close this so we can keep the issue tracker actionable. Thanks for starting this discussion!
