### ISSUE TITLE
`ruff.flake8-type-checking` Does not work with `FastAPI`

### ISSUE THREAD

**Issue by Tomperez98** [astral-sh/ruff#6137]
## Context

Command: `ruff --fix-only src`
```toml
[tool.ruff.flake8-type-checking]
runtime-evaluated-base-classes = [
    "pydantic.BaseModel",
    "mashumaro.mixins.orjson.DataClassORJSONMixin",
    "fastapi.responses.Response",
]
runtime-evaluated-decorators = ["fastapi.APIRouter.get", "router.get"]
```
Ruff version: `ruff 0.0.278`

```python3
if TYPE_CHECKING:
    import uuid

@router.get(path="/{user_id}")
async def get_user(user_id: uuid.UUID) -> Response:
    ...
```

## Error message

```bash
pydantic.errors.PydanticUndefinedAnnotation: name 'uuid' is not defined
```

## Expected behavior

```python3
import uuid
```
should be moved out from the `TYPE_CHECKING` block since is used by fastapi at runtime. I don't know how to configure ruff to fix thin

**Comment by Tomperez98** [comment]
```python3
from fastapi import APIRouter

if TYPE_CHECKING:
    import uuid

router = APIRouter()

@router.get(path="/{user_id}")
async def get_user(user_id: uuid.UUID) -> Response:
    ...

**Comment by Tomperez98** [comment]
@charliermarsh Sorry, I wasn't clear. But it's defined within the same file

**Comment by charliermarsh** [comment]
The best we can support right now is: put your router in a separate file (e.g., assume it's called `routers.py`), then import it where you use it, like:

```python
from routers import router

if TYPE_CHECKING:
    import uuid

@router.get(path="/{user_id}")
async def get_user(user_id: uuid.UUID) -> Response:
    ...
```

Then, you can mark it as runtime-required with:

```toml
[tool.ruff.flake8-type-checking]
runtime-evaluated-decorators = ["routers.router.get"]
```

In short, the paths included the configuration file need to be paths to imported symbols, rather than just plain names. It's a known limitation (https://github.com/astral-sh/ruff/issues/5486) right now that the symbol has to be defined in another file and imported in order to match, but it goes beyond this issue I think. Hopefully this is somewhat helpful though.
