### ISSUE TITLE
COM812 Appears to Still Not Quite Be Right

### ISSUE THREAD

**Issue by benjamin-kirkbride** [astral-sh/ruff#6525]
It seems that COM812 does not like when arguments overflow to a new line, but are still on a single line. It wants a trailing comma, which then activates [black's magic trailing comma](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma).

My expectation is that it would not have a problem with this.

![image](https://github.com/astral-sh/ruff/assets/3373830/91da8cbe-2a5d-4cab-ab41-5d69b3aef566)

```python3
long_variable_name_ayyyyyyyy = 1
other_long_variable_nameeeee = 2

hhhhhhhhhhh, jjjjjjjj, kkkkkkkk, llllllllll = range(
    long_variable_name_ayyyyyyyy, other_long_variable_nameeeee
)
```

Related to #3303

**Comment by zanieb** [comment]
@benjamin-kirkbride would you mind fixing the formatting of your post (i.e. render the image) and including a minimal reproducible example as well as a description of what's happening vs what you expect?

**Comment by benjamin-kirkbride** [comment]
@zanieb done :M

**Comment by charliermarsh** [comment]
I believe this is working as intended -- it's the same behavior and reasoning as https://github.com/asottile/add-trailing-comma.

**Comment by benjamin-kirkbride** [comment]
```diff
 x(
     arg,
-    arg
+    arg,
 )
```

This makes sense to me^

```
 x = [
-    1, 2, 3
+    1, 2, 3,
 ]
```

This conflicts with `black`^

I guess disabling it is easy enough though, if this is truly intended behavior.

**Comment by charliermarsh** [comment]
Yeah I think this is as-expected -- I believe the rule is intended to add trailing commas to any call that spans multiple lines in the interest of consistency and generating clear diffs, regardless of whether the arguments _themselves_ are wrapped over multiple lines. It's not necessarily intended to adhere to Black's preferences in any specific way.

**Comment by benjamin-kirkbride** [comment]
Thanks for taking a look!

**Comment by steve-mavens** [comment]
Is it worth documenting when rules conflict with black? I (and I suspect many others) use both black and ruff, and it would be nice not to have to look through ruff issues to establish that the conflict is a feature, not a bug :-)

**Comment by charliermarsh** [comment]
@steve-mavens - Our documentation on rules that conflict with Ruff's formatter should be accurate for Black too: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules

**Comment by anilsg** [comment]
I can't help posting here again despite the years of discussion since I find the particular scenario (below) undesirable and I don't see recognition of its merits recognised explicitly enough for me to believe it's been properly considered.

[I interpret issue #8555 as not coincident with this scenario since #8555 is being discussed as applicable to situations only where a function call is initially formatted across multiple lines, therefore I post here instead of there.]

I have a function call with multiple arguments initially formatted on one line, where `black` reformats the arguments on a single line without a trailing comma which triggers COM812:

```python
    some_kind_of_date: datetime.date = Field(
        datetime.date.min, description="We normally expect fairly lengthy sentences of words here."
    )
```

If I were to add a trailing comma `black` takes this as an indication to format the arguments on one line each which also deals with the COM812:

```python
    some_kind_of_date: datetime.date = Field(
        datetime.date.min,
        description="We normally expect fairly lengthy sentences of words here.",
    )
```

It seems to me that `black` is respecting the programmer's intention to format with less vertical space but still supports both approaches. This does not seem to be a 'black' "preference". These are two distinct formats triggered by hints from the programmer derived from the input formatting (all on one line, no trailing comma supplied).

I evaluate Ruff's behaviour against the stated goals of COM812 which are "consistency" and "generating clear diffs", or just ["diff size"](https://docs.astral.sh/ruff/rules/missing-trailing-comma/).

I felt it's not been acknowledged that the addition of a trailing comma in the single line scenario does *not* support "clearer diffs" as is usually meant, since the addition of another argument on a single line already alters that line so no diff lines are saved. The trailing comma only saves diff lines if the arguments are also placed on multiple lines. To be consistent, if Ruff is going to insist on a trailing comma (because clearer diffs) then Ruff should also force multiple line arguments.

Otherwise, I'm personally not clear what other scenarios "consistency" refers to since that is a relative term and this scenario is somewhat different from multiple lines of single arguments or what-have-you.

I would expect behaviour in accordance with the stated goals would be to not insist on a trailing comma where multiple arguments all fit on a single line and programmer has hinted that vertical space should be minimised.

If this argument is valid I'd be happy to formulate this specific scenario as an issue for consideration.
