### ISSUE TITLE
distutils is no longer in stdlib since Python 3.12 (PEP 632)

### ISSUE THREAD

**Issue by dlech** [astral-sh/ruff#6539]
Currently, when ruff sorts imports, `distutils` is grouped with other standard library packages. However, it has long been deprecated and has been removed in Python 3.12. https://peps.python.org/pep-0632/

It should now be sorted with 3rd-party packages.

Current behavior:

```python
import os
from distutils.command.install_headers import install_headers as _install_headers

from setuptools import setup
```

Expected behavior:

```python
import os

from distutils.command.install_headers import install_headers as _install_headers
from setuptools import setup
```

**Comment by charliermarsh** [comment]
I believe we've already implemented this -- we treat `distutils` as third-party if your minimum Python version is set to 3.12. Otherwise, it's treated as standard library, which seems correct to me.

E.g., given the above input, if you run `ruff check foo.py --isolated --select I --fix --target-version py312`, you get:

```python
import os

from distutils.command.install_headers import install_headers as _install_headers
from setuptools import setup
```

**Comment by dlech** [comment]
Thanks. It probably should have occurred to me to try changing the target version first. 😄
