### ISSUE TITLE
Ruff reports F704 `await` statement outside of a function for notebooks

### ISSUE THREAD

**Issue by david-waterworth** [astral-sh/ruff#6584]
In notebooks `await` is allowed in a cell (i.e. outside of a function), but `ruff` reports F704 - see also https://github.com/microsoft/pylance-release/issues/1754 and https://ipython.readthedocs.io/en/stable/interactive/autoawait.html

**Comment by charliermarsh** [comment]
Wow, interesting, TIL. Thanks for filing.

**Comment by dhruvmanila** [comment]
Interesting! It also seems that this can be disabled using `%autoawait False` or using `c.InteractiveShell.autoawait` in the config file.

I'm not sure what the long term solution would be but one idea is to store these as a context while processing the Notebook and then using that in some kind of a middleware to filter out such diagnostics. Or, instead of middleware this context can be passed around to the checkers. For example, in this example the context would give us information if `autoawait` is disabled or not. This will still be limited as it can be disabled in the config file.
