### ISSUE TITLE
Formatter: Optional empty line after class docstring

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ruff#6675]
This comes up frequently in the django project. 

**Input**

```python
class UnaryPredicate(GEOSFuncFactory):
    "For GEOS unary predicate functions."
    argtypes = [GEOM_PTR]

class UnaryPredicate2(GEOSFuncFactory):
    "For GEOS unary predicate functions."

    argtypes = [GEOM_PTR]
```

**Black**
Black preserves up to 1 empty line after the class docstring but doesn't insert one if it is missing. 

```python
class UnaryPredicate(GEOSFuncFactory):
    "For GEOS unary predicate functions."
    argtypes = [GEOM_PTR]

class UnaryPredicate2(GEOSFuncFactory):
    "For GEOS unary predicate functions."

    argtypes = [GEOM_PTR]
```

Same as input

**Ruff**

```python
class UnaryPredicate(GEOSFuncFactory):
    "For GEOS unary predicate functions."

    argtypes = [GEOM_PTR]

class UnaryPredicate2(GEOSFuncFactory):
    "For GEOS unary predicate functions."

    argtypes = [GEOM_PTR]
```

**Comment by MichaReiser** [comment]
@charliermarsh or is this an intentional deviation?

**Comment by charliermarsh** [comment]
It's because they're not triple-quoted: https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AJBALFdAD2IimZxl1N_WlXnON2nzOca5LMGDo9GYE1ODkqIAyq73A8oR_lVu7cIGYXERZR58hzQfd7zy8FfGyoz8UlHKY2aYfSKHZcFM6oCxcH3eZk2nzD2XJl_rlpCTBUKUPpJml2T4JHYkPhQZdj-bhtRNiZ211pQEWr0CCug01xQmKwlKDZvj9vN_Y6_09SHsus6upsaeCTSSfpujzZ3hI8H02mwmyCQktofPmEjG6uUQe3PAAAAAABpT3p1RnP9TgABzQHCBAAAVn4OiLHEZ_sCAAAAAARZWg==. In general, the newline after the class docstring is not optional, but Black doesn't consider these to be docstrings for that purpose. It is intentional right now.

**Comment by MichaReiser** [comment]
Hmm I see. It's one of the most common differences that we have todo, besides parenthesizing strings/identifiers, and something else that I forgot.

**Comment by charliermarsh** [comment]
We can easily change it to improve compatibility, though it does feel like a bug in Black. (I don't see why that wouldn't be formatted as a docstring when it is in fact a docstring.)

**Comment by MichaReiser** [comment]
I'm closing this for now, as it is a documented deviation. We can reconsider based on user feedback.
