### ISSUE TITLE
Implement `django-upgrade`

### ISSUE THREAD

**Issue by tjkuson** [astral-sh/ruff#6927]
I think [`django-upgrade`](https://github.com/adamchainz/django-upgrade) would be a good complement to the pre-existing Django-related ruff rules.

**Comment by browniebroke** [comment]
It will require adding a plugin specific setting as `django-upgrade` has a `--target-version` option for the Django version to target.

**Comment by ulgens** [comment]
I'd like to see `django-upgrade` too. It feels weird having `pyupgrade` but not `django-upgrade`.

**Comment by adamchainz** [comment]
As the django-upgrade author, I am a little concerned if Ruff reimplements it without dedicated developers who’ll update it for new fixers.

The Django community is gradually getting used to django-upgrade, and @carltongibson has even suggested making it an official tool. A few times now, contributors to Django have been able to implement a parallel fixer in django-upgrade, reducing the migration cost for changes. It’s unlikely that most Django contributors would be able to do the same in Ruff, since it uses Rust.

**Comment by carltongibson** [comment]
Thanks for the ping Adam. 

Yes, part of the whole idea is that PR authors can either implement fixers, or work closely with others who can, as the PR is being made. That seems to require close integration with Django, rather than moving further away. 

Also, from a ruff POV, Django Upgrade is something you run once per major version of Django, so once every 8 months at most, rather than on every save, so Ruff's selling point of speed isn't relevant. From the outside it doesn't seem to fit.

**Comment by nijel** [comment]
I don't think running once in 8 months is something reasonable to do. You want to have it applied to new code and anything what is not automated tends to be forgotten. Also django-upgrade is being improved at a different pace than Django releases. I'd love to see it included in ruff, but even if it is not, I would run it in pre-commit.

**Comment by charliermarsh** [comment]
Thanks @adamchainz and @carltongibson -- that makes sense! I wouldn't want to draw energy or attention away from an official resource like that, so we'll avoid re-implementing this one.

I could imagine us adding a few of the rules that look helpful on a continuous basis though (like automatically adding the `on_delete` keyword argument), we could consider adding those to our existing Django rule set.
