### ISSUE TITLE
Formatter undocumented deviation: annotation wrapping

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#7315]
Black formatting
```python
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb: Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = (
    Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb()
)
```
Ruff formatting
```python
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb: (
    Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
) = Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb()
```

Use ruff 0.0.289.
Both are set to a line length of 100.

**Comment by MichaReiser** [comment]
Thanks for reporting this deviation. Black seems to preserve parentheses in type annotation positions without ever introducing new parentheses. 

This is inconsistent with other places where expression appear as a direct child of a statement (other than expression statement) where Black prefers to strip any unnecessary parentheses (and applies the custom "can omit parentheses" layout). 

This can be solved "easily" by changing this line to use `annotation.format()` instead of `maybe_parenthesize` but it means that Ruff is more likely to exceed the line width

https://github.com/astral-sh/ruff/blob/c05e4628b1d385d106e7e3d355f5d1d76fbfe401/crates/ruff_python_formatter/src/statement/stmt_ann_assign.rs#L22-L30


This is probably related to https://github.com/astral-sh/ruff/issues/7322

**Comment by MichaReiser** [comment]
Copied over from #7322 

> I can see how Black's formatting may seem better but Black's code exceeds the configured line width of 100, whereas Ruff's formatting stays in the limit. 

> Black is also a bit inconsistent here because it uses the same formatting as ruff if you change this to an assignment:

  ```python
  animation_data = (
	  bpy.types.AnimData
  )  # TODO(jonathan): Change to Optional when fake-bpy-module is updated
  ```

> I propose that we stick to Ruff's layout because:
>  * It is more consistent with other syntax
>  * It stays within the configured line length


> I'll leave this open for now to let other people chime in.

**Comment by charliermarsh** [comment]
This is a known deviation -- can be closed once it's documented.
