### ISSUE TITLE
Formatter undocumented deviation: multi assignment wrapping

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#7317]
Black formatting
```python
def from_user_altitude_range_to_px4_altitude_range(
    altitude_range: Tuple[float, float],
) -> Tuple[int, int]:
    user_minimal_coordinate, user_maximal_coordinate = (0.0, 0.0, altitude_range[0]), (
        0.0,
        0.0,
        altitude_range[1],
    )
```
Ruff formatting
```python
def from_user_altitude_range_to_px4_altitude_range(
    altitude_range: Tuple[float, float],
) -> Tuple[int, int]:
    user_minimal_coordinate, user_maximal_coordinate = (
        (0.0, 0.0, altitude_range[0]),
        (
            0.0,
            0.0,
            altitude_range[1],
        ),
    )
```
Use Ruff 0.0.289 with line length 100.

**Comment by zanieb** [comment]
For what it's worth, I think the Ruff formatting is more readable in this example.

**Comment by JonathanPlasse** [comment]
I am reporting all deviations I come across.

**Comment by charliermarsh** [comment]
Thanks @JonathanPlasse! That’s great and the intended workflow. We’ll collect undocumented deviations, then make decisions on whether to address them or not.

**Comment by MichaReiser** [comment]
Thanks for reporting this deviation. This is an intentional deviation that I'm open to discussing and that we forgot to document. 

Ruff parenthesizes tuples except in a few places, whereas Black strips the parentheses in many places. 

```python
# Black
def from_user_altitude_range_to_px4_altitude_range():
    user_minimal_coordinate, user_maximal_coordinate = (0.0, 0.0, altitude_range[0]), (
        0.0,
        0.0,
        altitude_range[1],
    )

    (0.0, 0.0, altitude_range[0]), (
        0.0,
        0.0,
        altitude_range[1],
    )

    assertEquals(0.0, 0.0, altitude_range[0]),

# Ruff
def from_user_altitude_range_to_px4_altitude_range():
    user_minimal_coordinate, user_maximal_coordinate = (
        (0.0, 0.0, altitude_range[0]),
        (
            0.0,
            0.0,
            altitude_range[1],
        ),
    )

    (
        (0.0, 0.0, altitude_range[0]),
        (
            0.0,
            0.0,
            altitude_range[1],
        ),
    )

    (assertEquals(0.0, 0.0, altitude_range[0]),)

```

Our reasoning behind requiring the parentheses it otherwise can be very hard to spot that it is a tuple. For example, would you have noticed that the `assertEquals(0.0, 0.0, altitude_range[0]),` is a "useless" tuple? I did not and neither did some contributors to the django project https://github.com/django/django/pull/17181. That's why I propose keeping Ruff's formatting but I'm interested in getting more feedback on this (ideally from other projects trying ruff, are there places where this formatting looks worse?)
