### ISSUE TITLE
Formatter undocumented deviation: remove parenthesis

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#7320]
Black formatting
```python
def update_emission_strength(self: "Lightshow", context: bpy.types.Context) -> None:  # noqa: ARG001
    (
        get_rgbw_emission_node_tree(self)
        .nodes["Emission"]
        .inputs["Strength"]
        .default_value  # pyright: ignore
    ) = (self.emission_strength * 2)
```
Ruff formatting
```python
def update_emission_strength(self: "Lightshow", context: bpy.types.Context) -> None:  # noqa: ARG001
    (
        get_rgbw_emission_node_tree(self).nodes["Emission"].inputs["Strength"].default_value  # pyright: ignore
    ) = self.emission_strength * 2
```
Ruff 0.0.289, line-length 100

The pragma deviation is documented, but not the removal of parenthesis.

I prefer the Ruff formatting.

**Comment by MichaReiser** [comment]
There are two differences here:

1. Ruff splits the call chain differently because of the `pyright: ignore` comment. I think the current formatting is fine because enforcing black's layout can be wrong if you intend to document the whole call chain (and not just the last attribute). 
2. Black seems to parenthesize the right if the assignment target doesn't fit, regardless of whether the assigned value was parenthesized before. Adding these parentheses seems unnecessary in my view. 


```python
# Blacked code

def update_emission_strength():
    (
        get_rgbw_emission_node_tree(self)
        .nodes["Emission"]
        .inputs["Strength"]
        .default_value  # pyright: ignore
    ) = (self.emission_strength * 2)


def update_emission_strength():
    (
        get_rgbw_emission_node_tree(self)
        .nodes["Emission"]
        .default_value
    ) = (self.emission_strength * 2)
    
def update_emission_strength():
    (
        get_rgbw_emission_node_tree(self)
        .nodes["Emission"]
        .default_valueeeeeeeeeeeeee
    ) = (self.emission_strength * 2)
    
def update_emission_strength():
    (
        get_rgbw_emission_node_tree(self)
        .nodes["Emission"]
        .default_valueeeeeeeeeeeeee
    ) = self.emission_strength * 2

    
def update_emission_strength():
    (
        get_rgbw_emission_node_tree(self)
        .nodes["Emission"]
        .default_valueeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    ) = (self.emission_strength * 2)
```

**Comment by charliermarsh** [comment]
The parentheses we're considering an intentional deviation. Can be closed once it's documented.

The comment positioning deviation is expected because we ignore suppression comments when computing line length. (If you change it to some other comment, we use the same formatting as Black, apart from the extra parentheses on the RHS.) We're not planning to change this for the Beta, but we'll revisit based on feedback around suppression comment handling more generally.
