### ISSUE TITLE
Formatter incompatibility: extra parentheses around binary expression

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#7431]
Given:

```python
if True:
    if True:
        if True:
            if True:
                msg += " " + _(
                    "Since the role is not mentionable, it will be momentarily made mentionable "
                    "when announcing a streamalert. Please make sure I have the correct "
                    "permissions to manage this role, or else members of this role won't receive "
                    "a notification."
                )
```

Ruff formats as:

```python
if True:
    if True:
        if True:
            if True:
                msg += (
                    " "
                    + _(
                        "Since the role is not mentionable, it will be momentarily made mentionable "
                        "when announcing a streamalert. Please make sure I have the correct "
                        "permissions to manage this role, or else members of this role won't receive "
                        "a notification."
                    )
                )
```

Black formats as:

```python
if True:
    if True:
        if True:
            if True:
                msg += " " + _(
                    "Since the role is not mentionable, it will be momentarily made mentionable "
                    "when announcing a streamalert. Please make sure I have the correct "
                    "permissions to manage this role, or else members of this role won't receive "
                    "a notification."
                )
```

(Apologies for all the `if True:`, easiest way to preserve the indentation depth.)

Sourced from https://github.com/astral-sh/ruff/issues/7394.

Other examples:

* https://github.com/astral-sh/ruff/issues/7420

**Comment by MichaReiser** [comment]
The issue here is that the string itself exceeds the line width. Black falls back to the unparenthesized layout if the content doesn't fit even after adding parentheses. 

Our `BestFit` layout mimics this behavior for top-level strings, number literals, identifiers, and non-fluent attribute chains. 

https://github.com/astral-sh/ruff/blob/2d9b39871febdef1c5db75a2c9673dabcb86fbc1/crates/ruff_python_formatter/src/expression/parentheses.rs#L23-L26

We would need to apply the `BestFit` everywhere if we want to match Black's formatting but that comes at a considerable performance cost (`BestFit` is expensive because of allocations and additional measurements necessary by the printer). I also vaguely remember that it causes problems because `BestFit` results in a "break left-to-right" rather than our default "right-to-left", causing formatting mismatches further down. 

I'm not sure if its worth supporting this layout. I'm leaning towards finding ways to break problematic content a more sustainable approach that results in better readability and avoids the extra complexity (okay, requires complexity elsewhere, but doesn't increase the complexity of maybe_parenthesize which is rather involved). 

* Break strings at word boundaries similar to Black's preview style. This solves the problem here because the string can then made fit (by also adding parentheses)
* Break long non-fluent attribute chains similar to Prettier.

**Comment by MichaReiser** [comment]
I haven't yet found a solution to this and I don't feel up to the task today. The issue is, as explained above, that Ruff measures if all lines fit and only then avoids adding the necessary parentheses. 

Black on the other hand only tests if all lines that are not parenthesized fit. 

```python
long_kwargs_single_line = a + my_function(
    foo="test, this is a sampleddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    bar=b,
    baz=c,
)

if True:
    if True:
        if True:
            if True:
                msg += " " + _(
                    "Since the role is not mentionable, it will be momentarily made mentionable "
                    "when announcing a streamalert. Please make sure I have the correct "
                    "permissions to manage this role, or else members of this role won't receive "
                    "a notification."
                )


@extremely_long_variable_name_that_doesnt_fit := complex.expression(with_long="arguments_value_that_wont_fit_at_the_end_of_the_line")
def f():
    ...
```

I'm not quite sure how to model this with `FitsExpanded`. Simply ignoring line width overflows isn't sufficient because groups to the left stop breaking when they should. So there needs to be some form of mechanism that limits the *skipping* to only when measuring the outermost group, but not when measuring inner groups. 

I tried to do something along these lines with `StartAllowOverflow` but without too much success (results in stability errors, I believe because measuring the same group now yields inconsistent results). I think it is related that the `optional_parentheses` being rendered in `flat` mode but nested groups must still be measured in expanded.
