### ISSUE TITLE
E501 doesn't work in certain cases

### ISSUE THREAD

**Issue by yaroslavsadin** [astral-sh/ruff#8922]
```
$ ruff --version
ruff 0.1.6
```

No custom TOML config used.

Good code snippet:
```python
{
    i: i for i in ['somtehingverylongsomtehingverylongsomtehingverylongsomtehingverylongsomtehingverylongsomtehingverylongsomtehingverylong']
}
```
```console
$ ruff --select=E501 test.py
test.py:2:89: E501 Line too long (141 > 88)
Found 1 error.
```

Bad code snippet:
```python
{
    i: i for i in
    ['somtehingverylongsomtehingverylongsomtehingverylongsomtehingverylongsomtehingverylongsomtehingverylongsomtehingverylong']
}
```
```console
$ ruff --select=E501 test.py
$
```

**Comment by charliermarsh** [comment]
Thanks for the clear issue. I think this is roughly the same as https://github.com/astral-sh/ruff/issues/8383 and there's some 
more commentary in that issue + a few ideas for improvement. The gist of it is that if a line doesn't contain any splittable whitespace, we avoid flagging E501, which is more often helpful than hurtful, since a line without splittable whitespace tends to be, e.g., a single long URL or other long token. In this case, though, we should _probably_ be flagging E501, since we can split on the bracket at least.

**Comment by charliermarsh** [comment]
(Closing to merge with #8383.)
