### ISSUE TITLE
Autotyping fails to account for implicit returns

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#8942]
Given:

```python
def func(x: int):
    if x:
        return 1
```

We infer a return type of `int`, rather than `Optional[int]`.

**Comment by charliermarsh** [comment]
@MichaReiser - Do you think it's feasible to use the unreachable code graph to implement this?

**Comment by MichaReiser** [comment]
> @MichaReiser - Do you think it's feasible to use the unreachable code graph to implement this?

Using the control flow graph is an option. Although I fear that building the control flow graph just for this might be a bit overkill because we aren't interested in control flows, but only care about exit nodes of the function. I would need to look into it again but from what I remember is that Hindley milner is AST based. We could potentially implement a subset of it. But it heavily depends on how accurate the type analysis should be.
