### ISSUE TITLE
Fuzz proposal: fuzz target for formatting

### ISSUE THREAD

**Issue by manunio** [astral-sh/ruff#9169]
Hi, Would be interested in  a fuzz target that formates the code twice and checks for inconsistencies between them, something which is done here:
https://github.com/astral-sh/ruff/blob/c944d23053fe84e63a7515c75a50ce46b63dc2e0/crates/ruff_python_formatter/tests/fixtures.rs#L213

For example something like this:
```rust
#![no_main]

use libfuzzer_sys::{fuzz_target, Corpus};
use ruff_python_formatter::{format_module_source, PyFormatOptions};
use similar::TextDiff;


fn assert_difference(formatted: &str, reformatted: &str) {
    if reformatted != formatted {
        let diff = TextDiff::from_lines(formatted, reformatted)
            .unified_diff()
            .header("Formatted once", "Formatted twice")
            .to_string();
        panic!(
            r#"Reformatting the formatted code a second time resulted in formatting changes.
---
{diff}---

Formatted once:
---
{formatted}---

Formatted twice:
---
{reformatted}---"#,);
    }
}


fn do_fuzz(case: &[u8]) -> Corpus {
    // throw away inputs which aren't utf-8
    let Ok(code) = std::str::from_utf8(case) else {
        return Corpus::Reject;
    };

    // format code twice
    let formatted = match format_module_source(code, PyFormatOptions::default()) {
        Ok(formatted) => formatted,
        Err(_) => return Corpus::Reject,
    };

    let reformatted = match format_module_source(formatted.as_code(), PyFormatOptions::default()) {
        Ok(reformatted) => reformatted,
        Err(_) => return Corpus::Reject,
    };

    assert_difference(formatted.as_code(), reformatted.as_code());

    Corpus::Keep
}


fuzz_target!(|case: &[u8]| -> Corpus { do_fuzz(case) });
```

**Comment by MichaReiser** [comment]
@qarmin did some fuzzing of the formatter in the past. See https://github.com/astral-sh/ruff/issues/7433

I don't know if the script they used is available somewhere. 

Overall,  we've found fuzzing a useful tool to improve Ruff's stability and it helped us find many stability issues before releasing ruff's formatter. However, fuzzers also discover issues that are very rare or close to non-existent in practice. That's why reporting and fixing all of them isn't necessary impactful for our users and is the reason why we prioritize real-world issues or new features over fuzzer issues (but this depends on the fuzzer issue).


What's most helpful for us is a list of triaged fuzzer issues. But I think triaging is hard to impossible without understanding how our formatter works. Having a way to run the fuzzer (by someone who can triage issues but doesn't know how fuzzing works) could, therefore, be helpful, if we can integrate it into our exsiting fuzzer infrastructure (see `fuzzer` directory).

**Comment by MichaReiser** [comment]
Yeah, go for it if you're interested in adding it to our existing fuzzer.

**Comment by addisoncrump** [comment]
Was this ever added? Formatter idempotency has proven to be super useful for bug detection in other projects (see @jasikpark's work with Prettier, my work with boa and Biome).

**Comment by addisoncrump** [comment]
@manunio: I think your fuzzer is a good start here, but the reformatting should never fail (instead should `panic!`) as we have a safety guarantee from the formatter to produce valid syntax. Do you want to open a PR? We can discuss further changes there.

**Comment by MichaReiser** [comment]
> I slept on it; I actually think both this and a [format validity fuzzer](https://github.com/biomejs/biome/blob/main/fuzz/fuzz_targets/rome_common.rs?rgh-link-date=2024-01-03T11%3A53%3A08Z#L61-L165) which [fuzzes to check that the formatter does not introduce linter errors](https://github.com/biomejs/biome/blob/main/fuzz/README.md?rgh-link-date=2024-01-03T11%3A53%3A08Z#rome_format_) would be good to add.

This sounds interesting. Especially to discover incompatibilities that aren't obvious. Although we may need to have a ignore list of rules that we know are not compatible. 

> Was this ever added? Formatter idempotency has proven to be super useful for bug detection in other projects (see @jasikpark's work with Prettier, my work with boa and Biome).

Honestly, I'm not sure but I think it would be valuable to have.
