### ISSUE TITLE
Ruff format - polars chaining

### ISSUE THREAD

**Issue by mlarcane** [astral-sh/ruff#9577]
First of all; thx for providing this neat framework! In our team, we write alot of polars code and we like to chain such that each new polars method "has it's own line" so to speak. We can't seem to find any configurations that allow for this. This is quite a big deal in data science in general, that people like to chain pandas and polars in this way.

Is there anything you can do on this end so it can be configured?

![ruff_format_polars](https://github.com/astral-sh/ruff/assets/154270233/c88272bf-b6cc-4420-986c-d370f509a515)

**Comment by MichaReiser** [comment]
Hy @mlarcane 

No, there's currently no way to configure method chaining but I know that method chaining has come up before (I also find Ruff's/Black's formatting hard to read). 

The main challenge with method chaining is that Black/Ruff try very hard to avoid (introducing) parentheses. But method chaining would require parentheses because of Python (a problem other languages don't have). 

I don't expect us to work on this anytime soon but I'll leave it open and track it as a style discussion.

**Comment by tmke8** [comment]
There could be magic parentheses (analogous to magic commas) which, if present, would tell the formatter to apply the "call chain style".

**Comment by mlarcane** [comment]
@tmke8 That would be awesome! Really dig the magic commas (for consistency).

**Comment by MartinBernstorff** [comment]
Related to #8598

**Comment by MichaReiser** [comment]
Thanks, @MartinBernstorff, for linking the issue. I did search for it before replying on the issue but failed to find it. 

I'll close this issue in favour of #8598
